var upcomingTrackListRace;var featureTrackListRace;var availableMenuTrackListRace;var favoriteMenuTrackListRace;var harnessMenuTrackListRace;var thoroughbredMenuTrackListRace;var greyhoundMenuTrackListRace;var resultdMenuTrackListRace;var featuredMenuTrackListRace;var nameTrackListCollectionAvailable="_trackListRaceAvailable";var nameTrackListCollectionUpcoming="_trackListRaceUpcoming";var nameTrackListCollectionFeatures="_trackListRaceFeatured";var nameTrackListCollectionResult="_trackListResult";var _trackListRaceAvailable;var _trackListRaceUpcoming;var _trackListRaceFeatured;var _trackListResult;var _flagStartSearch=false;var _modeByCountry=true;var _menuTrackOrder="";var UserAccessLastTime=null;var SessionTimeoutInSeconds=1200;var _isBlockRefresh=false;function AddInformationUpcomingTrackList(tableName,titleId,titleMessage,tablePrincipalId,headerTitleId){upcomingTrackListRace=new Object;upcomingTrackListRace.TableName=tableName;upcomingTrackListRace.TitleId=titleId;upcomingTrackListRace.TitleMessage=titleMessage;upcomingTrackListRace.TablePrincipalId=tablePrincipalId;upcomingTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationFeatureTrackList(tableName,titleId,titleMessage,tablePrincipalId,headerTitleId){featureTrackListRace=new Object;featureTrackListRace.TableName=tableName;featureTrackListRace.TitleId=titleId;featureTrackListRace.TitleMessage=titleMessage;featureTrackListRace.TablePrincipalId=tablePrincipalId;featureTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationAvailableMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){availableMenuTrackListRace=new Object;availableMenuTrackListRace.TableName=tableName;availableMenuTrackListRace.TitleId=titleId;availableMenuTrackListRace.TitleMessage=titleMessage;availableMenuTrackListRace.TableHeaderId=tableHeaderId;availableMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationFavoritieMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){favoriteMenuTrackListRace=new Object;favoriteMenuTrackListRace.TableName=tableName;favoriteMenuTrackListRace.TitleId=titleId;favoriteMenuTrackListRace.TitleMessage=titleMessage;favoriteMenuTrackListRace.TableHeaderId=tableHeaderId;favoriteMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationHarnessMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){harnessMenuTrackListRace=new Object;harnessMenuTrackListRace.TableName=tableName;harnessMenuTrackListRace.TitleId=titleId;harnessMenuTrackListRace.TitleMessage=titleMessage;harnessMenuTrackListRace.TableHeaderId=tableHeaderId;harnessMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationThoroughbredMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){thoroughbredMenuTrackListRace=new Object;thoroughbredMenuTrackListRace.TableName=tableName;thoroughbredMenuTrackListRace.TitleId=titleId;thoroughbredMenuTrackListRace.TitleMessage=titleMessage;thoroughbredMenuTrackListRace.TableHeaderId=tableHeaderId;thoroughbredMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationGreyhoundMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){greyhoundMenuTrackListRace=new Object;greyhoundMenuTrackListRace.TableName=tableName;greyhoundMenuTrackListRace.TitleId=titleId;greyhoundMenuTrackListRace.TitleMessage=titleMessage;greyhoundMenuTrackListRace.TableHeaderId=tableHeaderId;greyhoundMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationResultdMenuTrackListRace(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){resultdMenuTrackListRace=new Object;resultdMenuTrackListRace.TableName=tableName;resultdMenuTrackListRace.TitleId=titleId;resultdMenuTrackListRace.TitleMessage=titleMessage;resultdMenuTrackListRace.TableHeaderId=tableHeaderId;resultdMenuTrackListRace.HeaderTitleId=headerTitleId;}
function AddInformationFeaturedMenuTrackList(tableName,titleId,titleMessage,tableHeaderId,headerTitleId){featuredMenuTrackListRace=new Object;featuredMenuTrackListRace.TableName=tableName;featuredMenuTrackListRace.TitleId=titleId;featuredMenuTrackListRace.TitleMessage=titleMessage;featuredMenuTrackListRace.TableHeaderId=tableHeaderId;featuredMenuTrackListRace.HeaderTitleId=headerTitleId;}
function RefreshTrackListRace(tableName,titleId,titleMessage,tableHeaderId,autoRefresh){var addInformation=GetAddInformationBetSessionStorage();if(_isEnableRefresh){if(autoRefresh){Racebook.RefreshTracks(nameTrackListCollectionAvailable,nameTrackListCollectionUpcoming,nameTrackListCollectionFeatures,_sessionSSC,_token,addInformation,Refresh_CallBack);}
else{Racebook.RefreshTracks(nameTrackListCollectionAvailable,nameTrackListCollectionUpcoming,nameTrackListCollectionFeatures,_sessionSSC,_token,addInformation,OnlyRefresh_CallBack);}}
else{setTimeout(function(){RefreshTracks();},_timeToRefreshTracks*1000);}}
function OnlyRefresh_CallBack(response){if(response.error!==null){ShowLoginPage();return;}
eval(response.value);response=null;BindingInformationMenuUpcomingFeatured();displaySpaceSectionBetting();}
function Refresh_CallBack(response){if(response.error!==null){ShowLoginPage();return;}
eval(response.value);response=null;if(!DisableRenderMenuAndUpcomingInformationMobile()){BindingInformationMenuUpcomingFeatured();}
displaySpaceSectionBetting();FilterTrackList();setTimeout(function(){RefreshTracks();},_timeToRefreshTracks*1000);}
function DisableRenderMenuAndUpcomingInformationMobile(){if(_modePage==2&&_sectionIsShowingModeMobile==1){return true;}
else{return false;}}
function BindingInformationMenuUpcomingFeatured(){if(_trackListRaceFeatured!=undefined&&_trackListRaceFeatured.Tracks!=undefined){var _menuTrackListAvailableRace=new TrackMenuListRenderClass();var _trackListUpcomingRace=new TrackListRendererClass(0);var _trackListFeaturedRace=new TrackListRendererClass(1);_menuTrackListAvailableRace.SetModeByCountry(_modeByCountry);if(_menuTrackOrder!=''){_menuTrackListAvailableRace.SetOrderCountries(_menuTrackOrder);}
_menuTrackListAvailableRace.SetOrderMenuTrackList();_trackListRaceAvailable.SortOrderNameAndMTP();_trackListRaceUpcoming.SortOrderMTP();_trackListRaceFeatured.SortOrderMTP();var rowsToPaddingUpcoming=0;var rowsToPaddingFeatured=0;var hasToChangeLayoutUpcomingFeatured=false;if(window.innerWidth>=_maxWeightToFussionUpcomingFeatured){if(_trackListRaceFeatured!=undefined&&_trackListRaceFeatured.TotalCount()>_trackListRaceUpcoming.TotalCount()){if((_trackListRaceFeatured.TotalCount()-_trackListRaceUpcoming.TotalCount())==1&&_trackListRaceUpcoming.TotalCount()>0){rowsToPaddingUpcoming=1;}
else{if(window.innerWidth>=_maxWeightToFussionUpcomingFeatured){hasToChangeLayoutUpcomingFeatured=true;}}}
if(_trackListRaceUpcoming!=undefined&&_trackListRaceUpcoming.TotalCount()>_trackListRaceFeatured.TotalCount()){if((_trackListRaceUpcoming.TotalCount()-_trackListRaceFeatured.TotalCount())==1&&_trackListRaceFeatured.TotalCount()>0){rowsToPaddingFeatured=1;}
else{if(window.innerWidth>=_maxWeightToFussionUpcomingFeatured){hasToChangeLayoutUpcomingFeatured=true;}}}
if(hasToChangeLayoutUpcomingFeatured){if(_trackListRaceUpcoming.TotalCount()%2!=0){rowsToPaddingUpcoming=1;}
if(_trackListRaceFeatured.TotalCount()>1){if(_trackListRaceFeatured.TotalCount()%2!=0){rowsToPaddingFeatured=1;}}}}
_menuTrackListAvailableRace.ResetMenusAdded();_trackListUpcomingRace.SetButtonAccessId('dvUpcomingRaceAccess');_trackListUpcomingRace.SetTitleId(upcomingTrackListRace.TitleId);_trackListUpcomingRace.SetPrincipalTableId(upcomingTrackListRace.TablePrincipalId);_trackListUpcomingRace.SetTrackMsg(upcomingTrackListRace.TitleMessage);_trackListUpcomingRace.SetTotalRowToPadding(rowsToPaddingUpcoming);_trackListUpcomingRace.Show(upcomingTrackListRace.TableName,_trackListRaceUpcoming.Tracks);_trackListFeaturedRace.SetTitleId(featureTrackListRace.TitleId);_trackListFeaturedRace.SetPrincipalTableId(featureTrackListRace.TablePrincipalId);_trackListFeaturedRace.SetTrackMsg(featureTrackListRace.TitleMessage);_trackListFeaturedRace.SetTotalRowToPadding(rowsToPaddingFeatured);_trackListFeaturedRace.SetTrackTypeToLoad('FTR');if(window.innerWidth<_maxWeightToFussionUpcomingFeatured){if(window.innerWidth<_maxWeightToFussionUpcomingFeaturedForMobile){_menuTrackListAvailableRace.SetIsAvailableTrack(true);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('UPC');_menuTrackListAvailableRace.Show('',_trackListRaceUpcoming.Tracks);_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('FTR');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);}
else{_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('FTR');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);_trackListFeaturedRace.SetButtonAccessId('dvFeaturedRaceAccess');_trackListFeaturedRace.Show(featureTrackListRace.TableName,new Array());_menuTrackListAvailableRace.SetTrackTypeToLoad('UPC');_menuTrackListAvailableRace.Show('',new Array());ChangeUpcomingFeaturedRace('upcomming');$('#dvMainTrackListToBet').removeClass('sDvMainTrackModeMultiple');$('#dvMainTrackListToBet').addClass('sDvMainTrackModeSingle');$('#dvTrackListToBetZoneTop').addClass('sHideElement');$('#sDvTracksPadding').addClass('sHideElement');}}
else{$('#dvMainTrackListToBet').addClass('sDvMainTrackModeMultiple');$('#dvMainTrackListToBet').removeClass('sDvMainTrackModeSingle');_menuTrackListAvailableRace.Show('',new Array());_menuTrackListAvailableRace.SetTrackTypeToLoad('UPC');_menuTrackListAvailableRace.Show('',new Array());if(hasToChangeLayoutUpcomingFeatured){if(HasOneTrackFeatured(_trackListRaceFeatured.Tracks)){_trackListFeaturedRace.SetSingleCss('sDvSingleTableUpcomingFeatures sDvSingleTableUpcomingFeaturesOneRow');}
_trackListFeaturedRace.SetTitleHeaderId('lblMainFeaturedTop');_trackListFeaturedRace.SetButtonAccessId('dvFeaturedRaceAccessZoneTop');_trackListFeaturedRace.Show('tlbTracksListFeaturedZoneTop',_trackListRaceFeatured.Tracks);$('#dvFeaturedRaceToBet').addClass('sHideElement');$('#dvFeaturedRaceAccess').addClass('sHideElement');if(HasTrackFeatured(_trackListRaceFeatured.Tracks)){$('#dvTrackListToBetZoneTop').removeClass('sHideElement');}
else{$('#dvTrackListToBetZoneTop').addClass('sHideElement');}
$('#dvMainTrackListToBetZoneTop').addClass('sDvMainTrackModeSingle');$('#dvMainTrackListToBet').removeClass('sDvMainTrackModeMultiple');$('#dvMainTrackListToBet').addClass('sDvMainTrackModeSingle');$('#dvFeaturedRaceAccess').removeClass('sDvSpaceFeatured');$('#sDvTracksPadding').removeClass('sHideElement');if(_trackListRaceFeatured.Tracks.length==0){$('#dvFeaturedRaceToBetZoneTop').addClass('sHideElement');}
else{$('#dvFeaturedRaceToBetZoneTop').removeClass('sHideElement');}}
else{_trackListFeaturedRace.SetTitleHeaderId('lblMainFeatured');_trackListFeaturedRace.SetButtonAccessId('dvFeaturedRaceAccess');_trackListFeaturedRace.Show(featureTrackListRace.TableName,_trackListRaceAvailable.Tracks);$('#dvFeaturedRaceToBet').removeClass('sHideElement');$('#dvFeaturedRaceAccess').removeClass('sHideElement');$('#dvTrackListToBetZoneTop').addClass('sHideElement');$('#dvMainTrackListToBetZoneTop').removeClass('sDvMainTrackModeSingle');$('#dvMainTrackListToBet').removeClass('sDvMainTrackModeSingle');$('#dvMainTrackListToBet').addClass('sDvMainTrackModeMultiple');if($('#'+featureTrackListRace.TableName).html()!=''){$('#dvFeaturedRaceAccess').addClass('sDvSpaceFeatured');}
else{$('#dvFeaturedRaceAccess').addClass('sHideElement');}}}
if($('#_isAnonimous').val()==="0"&&$('#_favoriteMenuEnable').val()==="TRUE"){$('#tdTrackFavorite').removeClass('sHideElement');_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(true);_menuTrackListAvailableRace.SetTrackTypeToLoad('ALL');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);}
else{$('#tdTrackFavorite').addClass('sHideElement');}
_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('THB');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('HRN');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('GYN');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);if(!_modeByCountry){_menuTrackListAvailableRace.SetIsAvailableTrack(false);_menuTrackListAvailableRace.SetIsFavoriteMode(false);_menuTrackListAvailableRace.SetTrackTypeToLoad('INT');_menuTrackListAvailableRace.Show('',_trackListRaceAvailable.Tracks);}
_menuTrackListAvailableRace.CleanMenusAdded();_menuTrackListAvailableRace.SortOrderMenu();_menuTrackListAvailableRace=null;_trackListUpcomingRace=null;_trackListFeaturedRace=null;_trackListRaceFeatured=null;_trackListResult=null;}}
function HasOneTrackFeatured(_list){let tt=0;for(let p=0;p<_list.length;p++){if(_list[p].IsFeatured==="1"){tt++;}}
return tt===1;}
function HasTrackFeatured(_list){let tt=0;for(let p=0;p<_list.length;p++){if(_list[p].IsFeatured==="1"){tt++;}}
return tt>=1;}
function ShowResultTrackByEvent(trackEventId){setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.ShowTracksByEventResultInformation(trackEventId,nameTrackListCollectionResult,_sessionSSC,_token,addInformation,ShowResultTrackByEvent_CallBack);},100);}
function ShowResultTrackByEvent_CallBack(response){if(response.error!==null){return;}
eval(response.value);ShowWaitDialog(false);response=null;}
var alreadySet=false;function SetValidateSession(){if(!alreadySet){ValidateSession();}}
function ValidateSession(){if(_modePage==2&&_sectionIsShowingModeMobile!=0){alreadySet=true;var addInformation=GetAddInformationBetSessionStorage();Racebook.ValidateSession(_sessionSSC,_token,addInformation,ValidateSession_CallBack);}}
function ValidateSession_CallBack(response){if(response.error!==null){return;}
eval(response.value);response=null;setTimeout(function(){alreadySet=false;ValidateSession();},45*1000);}
function RefreshTracks(){if(!_isBlockRefresh){RefreshTrackListRace("","","","",true);}}
function LoadResultInformation(){var _menuTrackListResult=new TrackListResultRenderClass();_menuTrackListResult.SetTitleId(resultdMenuTrackListRace.TitleId);_menuTrackListResult.SetTrackMsg(resultdMenuTrackListRace.TitleMessage);_menuTrackListResult.Show(resultdMenuTrackListRace.TableName,_trackListResult.Tracks);_menuTrackListResult=null;}
function ChangeLaguange(controlSelect){var addInformation=GetAddInformationBetSessionStorage();var response=Racebook.ChangeLaguange(_sessionSSC,_token,addInformation,controlSelect.value);if(response.error!==null){return;}
eval(response.value);}
function ResetSessionAction(){if(UserAccessLastTime){clearInterval(UserAccessLastTime);}
UserAccessLastTime=setInterval("SessionTimeOutAction();",SessionTimeoutInSeconds*1000);}
function SessionTimeOutAction(){clearInterval(UserAccessLastTime);ShowLoginPage();}
function WatchAction(){$(document).click(function(e){ResetSessionAction();});$(document).keypress(function(e){var nodeName=e.target.nodeName;if('INPUT'==nodeName||'TEXTAREA'==nodeName){ResetSessionAction();}});}
function SearchClean(){var addInformation=GetAddInformationBetSessionStorage();Racebook.SearchClean(_sessionSSC,_token,addInformation);}
function SearchRunnerNameAndJockey(valueSearch,indexView){if(!_flagStartSearch){_flagStartSearch=true;var addInformation=GetAddInformationBetSessionStorage();ShowWaitDialog(true,$('#btnSearchRunner').offset().top-10,parseInt($('#dvSearchMenuTab').offset().left+($('#dvSearchMenuTab').width()/2),10));Racebook.SearchInSchedule(valueSearch,indexView,_searchType,_sessionSSC,_token,addInformation,nameTrackListCollectionAvailable,nameTrackListCollectionUpcoming,nameTrackListCollectionFeatures,SearchInSchedule_CallBack);}}
function SearchVideoStats(){var addInformation=GetAddInformationBetSessionStorage();ShowWaitDialog(true,$('#btnSearchRunner').offset().top-10,parseInt($('#dvSearchMenuTab').offset().left+($('#dvSearchMenuTab').width()/2),10));var response=Racebook.SearchInSchedule('','',_searchType,_sessionSSC,_token,addInformation,nameTrackListCollectionAvailable,nameTrackListCollectionUpcoming,nameTrackListCollectionFeatures);if(response.error!==null){return;}
eval(response.value);ShowWaitDialog(false);response=null;FilterTrackList();}
function ReloadFilterSearch(){if(_searchTypeFilter!==0){_searchType=2;SearchVideoStats();}}
function SearchInSchedule_CallBack(response){if(response.error!==null){return;}
eval(response.value);ShowWaitDialog(false);response=null;var _menuTrackSearch=new TrackMenuListRenderClass();_menuTrackSearch.ShowSearch(upcomingTrackListRace.TableName,searchCollection.Tracks);if(searchCollection.CurrentIndex==0){$('#dvLastSearch').parent().addClass('sTdMenuArrowDimentionDisable');}
else{$('#dvLastSearch').parent().removeClass('sTdMenuArrowDimentionDisable');}
if(searchCollection.CurrentIndex==(searchCollection.TotalIndex-1)){$('#dvNextSearch').parent().addClass('sTdMenuArrowDimentionDisable');}
else{$('#dvNextSearch').parent().removeClass('sTdMenuArrowDimentionDisable');}
_flagStartSearch=false;}