var _sessionSSC="";var _token="";var dateTimeNow=new Date();var showMessageBox=false;var showMessageBoxWithKey=false;var publicId="";var _showControls=new Array();var _timeToRefreshTracks=180;var _trackCodeOnSession=null;var _resultDatePickerId='';var _isHoverPopupMyAccount=false;var _isHoverPopupMyAccountTab=false;var _enableHoverPopupMyAccount=true;var _controlWeight=0;var _maxWeightToFussionUpcomingFeatured=1279;var _maxWeightToFussionUpcomingFeaturedForMobile=768;var _isAuthenticated=false;var _maxWeightToFussionUpcomingChanged=false;var _maxWeightToFussionUpcomingChangedFullSite=false;var _maxWeightToFussionUpcomingChangedMobile=false;var _modePage=0;var _sectionIsShowingModeMobile=0;var _sectionIsShowingModeMobileLast=0;var _isEnableRefresh=true;var _hasLoadExternalInformation=false;var _lastHashSelected='';var _hastTagSelection='';var _modeHashTagReloadMode=false;var _showExternalULRBetSlip=false;var _externalInformationBetSlipNoLoaded=false;var _useAlertInParent=false;var _enableFilterTrack=true;var _enableColapseTrackGroup=false;var _enableEditAmountToBetInBetslip=false;var _bannersURL=new Array();var _lastVideoURLLoaded="";$(document).ready(function(){getPublicId();startLayoutAplication();$('#dvMobileStreaming').hide();WatchAction();ResetSessionAction();_isAuthenticated=$('#_isAnonimous').val()=='0'?true:false;if(_isAuthenticated&&$('#_modeBetting').val()==='0'){if(_playerAutenticatedFromSportsbook){CloseDialogToSignInPlayer();}}
if(_isAuthenticated){if($('#_askConfirmationBet').val()=="FALSE"){$('#dvChAskConfirmationSubmit').addClass('sHideElement');}
if($('#_passwordConfirmationBet').val()=="FALSE"){$('#dvConfirmationSubmitPassword').addClass('sHideElement');}
$('#tblBetSlip').addClass('sDvAccounAutheticated');}
else{$('#dvChAskConfirmationSubmit').addClass('sHideElement');$('#dvConfirmationSubmitPassword').addClass('sHideElement');$('.sDvSearchOption').addClass('sHideElement');}
_controlWeight=window.innerWidth;RefreshTracks();if(isMobile.any()){$('#betAmount').prop('type','number');if(!_modeHashTagReloadMode){$('.aSendBet').prop('href','#');}}
else{$('#betAmount').prop('type','text');}
RefreshMTP("MTP",messages.MTP_Reached,true);$('#tdMenuUpcoming').click(function(){if($('#dvUpcomingRaceToBet').css('display')=='none'){ChangeUpcomingFeaturedRace('upcomming');$('#lblMainUpcoming').removeClass('LabelMenuTitleOver').addClass('LabelMenuTitleSelected');$('#lblMainFeatured').removeClass('LabelMenuTitleOver LabelMenuTitleSelected').addClass('LabelMenuTitle');$('#tdMenuFeatured').removeClass('sMenuUpcomingSelectedTab').addClass('sMenuUpcomingUnSelectedTab');$('#tdMenuUpcoming').removeClass('sMenuUpcomingUnSelectedTab').addClass('sMenuUpcomingSelectedTab');$('#trianguleTabTop').removeClass('trianguleTabRight').addClass('trianguleTabLeft');}});$('#tdMenuFeatured').click(function(){if($('#dvFeaturedRaceToBet').css('display')=='none'){ChangeUpcomingFeaturedRace('featured');$('#lblMainFeatured').removeClass('LabelMenuTitleOver').addClass('LabelMenuTitleSelected');$('#lblMainUpcoming').removeClass('LabelMenuTitleOver LabelMenuTitleSelected').addClass('LabelMenuTitle');$('#tdMenuUpcoming').removeClass('sMenuUpcomingSelectedTab').addClass('sMenuUpcomingUnSelectedTab');$('#tdMenuFeatured').removeClass('sMenuUpcomingUnSelectedTab').addClass('sMenuUpcomingSelectedTab');$('#trianguleTabTop').removeClass('trianguleTabLeft').addClass('trianguleTabRight');}});$('#tdMenuUpcoming').mouseover(function(){$('#lblMainUpcoming').removeClass('LabelMenuTitle').addClass('LabelMenuTitleOver');});$('#tdMenuFeatured').mouseover(function(){$('#lblMainFeatured').removeClass('LabelMenuTitle').addClass('LabelMenuTitleOver');});$('#tdMenuUpcoming').mouseleave(function(){if(!$('#lblMainUpcoming').hasClass('LabelMenuTitleSelected')){$('#lblMainUpcoming').removeClass('LabelMenuTitleOver LabelMenuTitleSelected').addClass('LabelMenuTitle');}});$('#tdMenuFeatured').mouseleave(function(){if(!$('#lblMainFeatured').hasClass('LabelMenuTitleSelected')){$('#lblMainFeatured').removeClass('LabelMenuTitleOver LabelMenuTitleSelected').addClass('LabelMenuTitle');}});$('#dvTblBetSplipCart').click(function(){if(_isAuthenticated){if(typeof shoppingCartEdit==="undefined"||(typeof shoppingCartEdit!=="undefined"&&!shoppingCartEdit.IsEditMode())){BetSlipClickAction();}
else{confirm(messages.lblPhoneConfirmCancelBetEdit,function(){shoppingCartEdit.EditTicketCancel();BetSlipClickAction();});}}
else{$("#dvPopupMyAccount").hide();}
resizeHeightFancyMyAccountPopup();});$('#dvTblBetSplipMyAccount').click(function(){if(_isAuthenticated){if(typeof shoppingCartEdit==="undefined"||(typeof shoppingCartEdit!=="undefined"&&!shoppingCartEdit.IsEditMode())){MyAccountClickAction();}
else{confirm(messages.lblPhoneConfirmCancelBetEdit,function(){shoppingCartEdit.EditTicketCancel();MyAccountClickAction();});}}
else{showMyAccountMenu(true);}
resizeHeightFancyMyAccountPopup();});$('#dvTblBetSplipMyAccount').mouseover(function(){_isHoverPopupMyAccountTab=true;setTimeout(function(){if(_enableHoverPopupMyAccount){showMyAccountMenu(false);}},250);});$('#dvTblBetSplipMyAccount').mouseleave(function(){_isHoverPopupMyAccountTab=false;setTimeout(function(){if(!_isHoverPopupMyAccount){$("#dvPopupMyAccount").hide();restoreFancyMyAccountPopup();}},500);});$('#dvTblBetSlipOpenBets').click(function(){if(_isAuthenticated){$('#dvTblBetSlipOpenBets').removeClass().addClass('sDvBetSlipOpenBetsActive');$('#dvTblBetSplipCart').removeClass().addClass('sTblBetSplipCartUnSelected');$('#dvTblBetSplipMyAccount').removeClass().addClass('sTblBetSplipMyAccountUnSelected');$("#dvMyAccount").hide();$("#dvPopupMyAccount").hide();$("#dvAskLoginBetSlip").hide();$("#dvBetSlip").show();if($('#_modeBetting').val()=='0'){$('#ucBetSlip_dvBetSlipImportantMessage').css('visibility','hidden');$('#ucBetSlip_dvBetSlipImportantMessage').css('height','0px');$('#ucBetSlip_dvBetSlipMessageEmpty').css('visibility','hidden');$('#ucBetSlip_dvBetSlipMessageEmpty').css('height','0px');$('.sDvBetSlipImportantMessage').hide();$('#ucBetSlip_trSendBet').hide();}
shoppingCart.HideBetSlipBetInformation();shoppingCartEdit.ShowBetSlipInformation();$("#dvOpenBets").show();if(shoppingCartEdit.CountBetEnable==0){$('#dvTblBetSplipCart').click();shoppingCart.GetshoppingCart(false);}}
else{$("#dvOpenBets").hide();}});$('#dvPopupMyAccount').mouseover(function(){_isHoverPopupMyAccount=true;});$('#dvPopupMyAccount').mouseleave(function(){setTimeout(function(){if(!_isHoverPopupMyAccountTab){$("#dvPopupMyAccount").hide();restoreFancyMyAccountPopup();}},500);});$('.sDvLoginInputUsername input').keypress(function(e){if(e.which==13){if($("#loginFormUsr").val()!==""&&$("#passwordFormUsr").val()!==""){$('#btnLogin').click();}
return false;}});$('.sDvLoginInputPassword input').keypress(function(e){if(e.which==13){if($("#loginFormUsr").val()!==""&&$("#passwordFormUsr").val()!==""){$('#btnLogin').click();}
return false;}});$("#dvMyAccounLogin").click(function(){$('#AskLoginClick').click();$("#dvPopupMyAccount").hide();restoreFancyMyAccountPopup();$("#dvMyAccount").hide();});$("#optActiveBets").click(function(){$('#dvMyAccountActiveBet > div').click();});$("#optFinalBets").click(function(){$('#dvMyAccountFinalBet > div').click();});$("#optResult").click(function(){$('#dvMyAccountRaceResult > div').click();});$("#optLogout").click(function(){ShowLogoutPage();});$("#dvMyAccountLogout > div").click(function(){ShowLogoutPage();});$("#btnSearchAdvanced").click(function(){RestartAndClearSearchInfomation();let win=window,doc=document,docElem=doc.documentElement,body=doc.getElementsByTagName('body')[0],x=win.innerWidth||docElem.clientWidth||body.clientWidth,y=win.innerHeight||docElem.clientHeight||body.clientHeight;var widthSearch=90*x/100;var heightFanxyToSet=510;if(widthSearch>parseFloat(430)){widthSearch='430px';}
else{widthSearch=widthSearch+'px';}
$.fancybox.open({'href':'#dvSearchTrackAdvance',autoSize:false,autoResize:true,padding:0,margin:0,width:widthSearch,height:heightFanxyToSet,closeSpeed:100,closeBtn:false,fitToView:false,topRatio:0.01,scrolling:'hidden',helpers:{overlay:{locked:true,closeClick:false}},beforeShow:function(){try{if(!window.isTop){window.parent.postMessage("boss.hideScrollBody","*");}}
catch(e){console.log("Problem notifying to parent windows. "+e);}
$('#inpSearchText').val('');FilterTrackList();$('#inpSearchRunnerNameJockey').val('');$('#dvSearchTabRunnerDriver').click();},afterShow:function(){$('#inpSearchRunnerNameJockey').focus();$('#dvMenuSearch').bind('mousewheel DOMMouseScroll',function(e){if(searchCollection&&searchCollection!==null)
searchCollection.ClearList();if(searchCollection.TotalIndex>0){if(wheelDirection(e)>0){SearchRunnerNameAndJockey('',searchCollection.LastIndex());}
else{SearchRunnerNameAndJockey('',searchCollection.NextIndex());}}});},afterClose:function(){ShowWaitDialog(false);try{if(!window.isTop){window.parent.postMessage("boss.showScrollBody","*");}}
catch(e){console.log("Problem notifying to parent windows. "+e);}}});});$("#dvLastSearch").click(function(){searchCollection.ClearList();SearchRunnerNameAndJockey('',searchCollection.LastIndex());});$("#dvNextSearch").click(function(){searchCollection.ClearList();SearchRunnerNameAndJockey('',searchCollection.NextIndex());});$('#dvSearchTabRunnerDriver').click(function(){if(!$('#dvSearchTabRunnerDriver').hasClass('sTblSearchTapSelected')){$('#dvSearchTabRunnerDriver').addClass('sTblSearchTapSelected');$('#dvSearchTabRunnerDriver').removeClass('sTblSearchTapUnSelected');$('#dvSearchTabTrack').removeClass('sTblSearchTapSelected');$('#dvSearchTabTrack').addClass('sTblSearchTapUnSelected');$('#inpSearchRunnerNameJockey').val('');_searchType=0;RestartAndClearSearchInfomation();}});$('#dvSearchTabTrack').click(function(){if(!$('#dvSearchTabTrack').hasClass('sTblSearchTapSelected')){$('#dvSearchTabTrack').addClass('sTblSearchTapSelected');$('#dvSearchTabTrack').removeClass('sTblSearchTapUnSelected');$('#dvSearchTabRunnerDriver').removeClass('sTblSearchTapSelected');$('#dvSearchTabRunnerDriver').addClass('sTblSearchTapUnSelected');$('#inpSearchRunnerNameJockey').val('');_searchType=1;RestartAndClearSearchInfomation();}});$('#btnSearchVideo').click(function(){SearchTracksVideoStats(this);});$('#btnSearchStats').click(function(){SearchTracksVideoStats(this);});$("#dvCloseAdvancedSearch").click(function(){$.fancybox.close();});$("#dvTblBetSplipCartMobile").click(function(){var heightFanxyToSet=window.innerHeight;$.fancybox.open({'href':'#dvShopCar',autoSize:false,autoResize:false,topRatio:0,leftRatio:1,padding:0,margin:0,top:200,width:'320px',height:'auto',openMethod:'changeIn',closeSpeed:100,closeBtn:false,fitToView:false,scrolling:'hidden',helpers:{overlay:{locked:true}},afterShow:function(){if(isInIframe()){$(".fancybox-overlay").css({"overflow":"hidden"});}
setTimeout(function(){$('#dvTblBetSplipCart').click();if($('.fancybox-wrap').height()>$('html').height()){$('html').height($('.fancybox-wrap').height());}},250);if(shoppingCart.IsEditMode()){shoppingCart.ShowHideBlockBetSlip(shoppingCart.EditPalayerIndexBetId(),true);}},afterClose:function(){$('#dvShopCar').show();resizeMainPage(0);$('html').css("height","");}});});$("#dvTblBetSplipMyAccountMobile").click(function(){var heightFanxyToSet=window.innerHeight;$.fancybox.open({'href':'#dvShopCar',autoSize:false,autoResize:false,topRatio:0,leftRatio:1,padding:0,margin:0,top:200,width:'320px',height:'auto',openMethod:'changeIn',closeSpeed:100,closeBtn:false,fitToView:false,scrolling:'hidden',helpers:{overlay:{locked:true}},afterShow:function(){if(isInIframe()){$(".fancybox-overlay").css({"overflow":"hidden"});}
setTimeout(function(){$('#dvTblBetSplipMyAccount').click();},250);if(shoppingCart.IsEditMode()){shoppingCart.ShowHideBlockBetSlip(shoppingCart.EditPalayerIndexBetId(),true);}},afterClose:function(){$('#dvShopCar').show();resizeMainPage(0);}});});$("#dvBetSlipClose").click(function(){$.fancybox.close();});if($('#dvRaceDetailInformation').css('display')!=='none'){$('#tdRaceViewDetailInformation > div > div').first().click();}
$("#lblTrack").click(function(){if(_modePage===2){if(isMobile.any()){window.location.href=window.location.href.substr(0,window.location.href.indexOf('#'))+"#TrackList";}
else{NavegateMobileVersion("Top",false);}}});$("#lblTrackNameRoot").click(function(){if(_modePage===2){if(isMobile.any()){window.location.href=window.location.href.substr(0,window.location.href.indexOf('#'))+"#RaceList";}
else{NavegateMobileVersion("Top",false);}}});$("#lblMeetingRoot").click(function(){if(_modePage===2){if(!isMobile.Samsung()){window.location.href=window.location.href.substr(0,window.location.href.indexOf('#'))+"#RaceList";}
else{NavegateMobileVersion("Top",false);}}});$("#lblRaceNumberRoot").click(function(){if(_modePage===2){_sectionIsShowingModeMobileLast=_sectionIsShowingModeMobile;_sectionIsShowingModeMobile=2;setMobileMode();}});$(window).mouseover(function(){$(".sDvHoverTrackMenu").parent().blur();$(".sDvHoverTrackMenu").removeClass('sDvHoverTrackMenu');});if(!_isAuthenticated){var htmlMessage;var messageBase=messages.lblMessageSignInBet;if($('#_anonimousLoginType').val()!="3"){htmlMessage="<span>"+messageBase.replace('{0}',messages.lblSignIn)+"</span>";}
if($('#_anonimousLoginType').val()=="3"){var strURL=$("#loginURL").val();htmlMessage='<span onclick=\"GoURLLogin(\''+strURL+'\');\" class=\"sSpSignInUrl\">'+messageBase.replace('{0}',messages.lblSignIn)+'</span>';}
$('.sDvAskLogin > div').html(htmlMessage);}
showMyAccountOptions();var availableIdJqueryHeader='#'+listControlsId.AvailableId;if(BLRPersonalization==personalization){if($('#AvailableField')){$('#AvailableField').text($(availableIdJqueryHeader)[0].defaultValue);}}
if($('#AvailableBetSlip')){$('#AvailableBetSlip').text($(availableIdJqueryHeader)[0].defaultValue);}
$('#betAmount').keypress(function(e){if(e.which===13){CallSendBet();}});$('#dvBox span').mouseover(function(){if(!isMobile.any()){showMessageBox=true;setTimeout(function(){if(showMessageBox){$('#spBoxinformation').text(messages.lblPoolDescriptionBox);$('#divBoxInformation').css('left',$('#dvBox').position().left+15);$('#divBoxInformation').css('top',$('#dvBox').position().top+$('#dvBox').height());$('#divBoxInformation').show();}},500);}});$('#dvBox span').mouseleave(function(){if(!isMobile.any()){showMessageBox=false;$('#spBoxinformation').text('');$('#divBoxInformation').hide();}});$('#tblBoxWithKey span').mouseover(function(){if(!isMobile.any()){showMessageBoxWithKey=true;setTimeout(function(){if(showMessageBoxWithKey){$('#spBoxinformation').text(messages.lblPoolDescriptionBoxKey);$('#divBoxInformation').css('left',$('#tblBoxWithKey').position().left+15);$('#divBoxInformation').css('top',$('#tblBoxWithKey').position().top+$('#tblBoxWithKey').height());$('#divBoxInformation').show();}},500);}});$('#tblBoxWithKey span').mouseleave(function(){if(!isMobile.any()){showMessageBoxWithKey=false;$('#spBoxinformation').text('');$('#divBoxInformation').hide();}});$('#boxInformationParlay').mouseover(function(){$('#spBoxinformation').text(messages.lblPoolDescriptionParlay);$('#divBoxInformation').css('left',$(this).position().left-10);$('#divBoxInformation').css('top',$(this).position().top+25);$('#divBoxInformation').show();});$('#boxInformationParlay').mouseleave(function(){$('#spBoxinformation').text('');$('#divBoxInformation').hide();});ChangeUpcomingFeaturedAccess(false);setTimeout(function(){if($('#_favoriteMenuColapse').val()=="TRUE"){$('#trMenuTitleTT_FavC_Fav').click();}
if(_enableColapseTrackGroup){if($('#_modeBetting').val()!='0'){$('#dvMenus .sDvMenuTrackListContent > div').hide();$('#dvMenus .sTdMenuArrowDimention > div').addClass('sTdBtnMaximize').removeClass('sTdBtnMinimize');}}
if($('#_preSelectMeetingInformation').val()!==''){var informationPreSelected=$('#_preSelectMeetingInformation').val().split('*');var trackIdPreselected=$($('.sIS_'+informationPreSelected[0])[0]).attr('id');var trackTypePreselected=$($('.sIS_'+informationPreSelected[0])[0]).attr('trackType');if(trackIdPreselected!=undefined&&trackIdPreselected!==''){if(trackTypePreselected!==undefined&&trackTypePreselected!==''&&informationPreSelected[1]!=undefined&&informationPreSelected[2]!=undefined){ShowTrackInformation(trackIdPreselected,informationPreSelected[2],informationPreSelected[1],'false',trackTypePreselected);$('#_preSelectMeetingInformation').val('');setTimeout(function(){$("#dtlRaces td").each(function(){if($(this).text()==informationPreSelected[2]){$(this).click();}});},500);}
else{$('#'+trackIdPreselected).click();}}
if(_modePage!==2&&!_hasLoadExternalInformation){_hasLoadExternalInformation=true;if(!isMobile.any()){LoadExternalInformationBetSlip();LoadExternalInformationUpcomingSports();LoadExternalInformationCasino();}}}
else{if(_modePage!==2&&!_hasLoadExternalInformation){_hasLoadExternalInformation=true;if(!isMobile.any()){LoadExternalInformation();LoadExternalInformationBetSlip();LoadExternalInformationUpcomingSports();LoadExternalInformationCasino();}}}
if($('#_loadExternalBetSlipMobile').val()=="1"){LoadExternalInformationBetSlip();}},300);$("#betAmount").on("click",function(){$(this).select();});$("#betAmount").change("click",function(){GenerateTotalCombination();});var lng=$('#_lng').val();var newlng='en-GB';if(lng==="es-ES"){newlng="es";}
else if(lng==="fr-FR"){newlng="fr";}
else if(lng==="de-DE"){newlng="de";}
else if(lng==="it-IT"){newlng="it";}
else if(lng==="zh-cn"){newlng="zh-CN";}
else if(lng==="ko-KR"){newlng="ko";}
else if(lng==="el-GR"){newlng="el";}
else if(lng==="sq-AL"){newlng="sq";}
if(newlng!==''){$.datepicker.setDefaults($.datepicker.regional[newlng]);}
if(isMobile.any()){if(_modePage===2){_hastTagSelection=location.hash.slice(1);window.addEventListener('popstate',function(e){_hastTagSelection=location.hash.slice(1);NavegateMobileVersion(_hastTagSelection,false);})
NavegateMobileVersion(_hastTagSelection,false);if(_hastTagSelection==''){location.hash='#TrackList';}}}
shoppingCart.ResetDivInformation(false);PhoneMode();if(_enableFilterTrack){$('#inpSearchText').on('input',function(event){FilterTrackList();});$('#inpSearchText').on('focus',function(event){$('#inpSearchText').select();});$('#inpSearchText').keydown(function(event){switch(event.which){case 13:if($(".sDvMenuTrackListContent a[style='display: table;']").length==1){$(".sDvMenuTrackListContent a[style='display: table;']").find('> div').click();}
break;default:break;}});}
else{$('#dvSearchTrack').hide();}
$("#btnSearchRunner").click(function(){var value=$('#inpSearchRunnerNameJockey').val();value=value.trim();if(value.length>1){SearchRunnerNameAndJockey($('#inpSearchRunnerNameJockey').val(),'');}
else{var aCellDiv=document.createElement("div");var tlbTracks=returnObjById('dvMenuContentListSearch');$(tlbTracks).html('');aCellDiv.innerHTML=messages.lblMessageValidSearch;aCellDiv.className="sDvSearchState";tlbTracks.appendChild(aCellDiv);}});$("#inpSearchRunnerNameJockey").keyup(function(e){var value=$('#inpSearchRunnerNameJockey').val();value=value.trim();if(value.length>2){SearchRunnerNameAndJockey($('#inpSearchRunnerNameJockey').val(),'');}
else{var aCellDiv=document.createElement("div");var tlbTracks=returnObjById('dvMenuContentListSearch');$(tlbTracks).html('');aCellDiv.innerHTML=messages.lblMessageValidSearch;aCellDiv.className="sDvSearchState";tlbTracks.appendChild(aCellDiv);}});SetComment();if(_enableRememberBet){LoadRememberBetSessionStorage();}
$("#aMenuScores, #aMenuPending, #aMenuGraded, #aMenuFigures, #aMenuTransactions").fancybox({autoScale:true,autoCenter:false,transitionIn:'none',transitionOut:'none',titleShow:false,type:'iframe',iframe:{preload:false},fitToView:false,afterLoad:function(){$.extend(this,{aspectRatio:false,width:'100%',height:'100%'});}});if(_integrationCode!==0){$('body').addClass("sDbInt");}});$(window).resize(function(){ChangeUpcomingFeaturedAccess(true);$.fancybox.update();UpdateDialogToSignInPlayerPhone();});$('.fancybox-overlay').scroll(function(){$.fancybox.close();});function AddBanner(id,url,isMobile){var indexBanner=_bannersURL.length;_bannersURL[indexBanner]=new Object();_bannersURL[indexBanner].Id=id;_bannersURL[indexBanner].URL=url;_bannersURL[indexBanner].IsMobile=isMobile;}
function SearchTracksVideoStats(controlBtn){if($('#'+controlBtn.id).hasClass('sTblSearchTapSelected')){$('#'+controlBtn.id).removeClass('sTblSearchTapSelected');}
else{$('#'+controlBtn.id).addClass('sTblSearchTapSelected');}
_searchTypeFilter=0;if($('#btnSearchVideo').hasClass('sTblSearchTapSelected')&&$('#btnSearchStats').hasClass('sTblSearchTapSelected')){_searchTypeFilter=3;}
else{if($('#btnSearchStats').hasClass('sTblSearchTapSelected')){_searchTypeFilter=2;}
if($('#btnSearchVideo').hasClass('sTblSearchTapSelected')){_searchTypeFilter=1;}}
if(_searchTypeFilter!==0){_searchType=2;SearchVideoStats();}
else{FilterTrackList();}}
function ShowBanner(){var addInformation=GetAddInformationBetSessionStorage();for(var pb=0;pb<_bannersURL.length;pb++){if(_bannersURL[pb].IsMobile=="0"&&(_modePage===0||_modePage===1)){if(_bannersURL[pb].Id=="dvBannerDeskBetSlip"&&_modePage===1){$('#'+_bannersURL[pb].Id).html('');}
else{Racebook.LoadExternalInformation("4","",_bannersURL[pb].Id,_bannersURL[pb].URL,_sessionSSC,_token,addInformation,ExternalBanner_CallBack);}}
else{if(_bannersURL[pb].IsMobile=="1"&&_modePage===2){Racebook.LoadExternalInformation("4","",_bannersURL[pb].Id,_bannersURL[pb].URL,_sessionSSC,_token,addInformation,ExternalBanner_CallBack);}
else{$('#'+_bannersURL[pb].Id).html('');}}}
LoadExternalInformationBetSlipVideo(_lastVideoURLLoaded,true);}
function ClearFilterSearch(){$("#inpSearchText").val('');FilterTrackList();}
function FilterTrackList(){if(_enableFilterTrack){var value=$("#inpSearchText").val();$('#dvMenus').removeClass('sDvSearchMode');$('#dvSearchTrack').removeClass('sDvSearchMode');$('#dvMenus .sDvMenuTrackListHeader').show();$('#dvMenus .sDvMenuTrackListToBetBlank').show();$('#dvMenus .sTlbTracksMenu a').show();$('#dvMenuTT_Fav').show();if(value!==''||_searchTypeFilter!==0){$('#dvMenus .sDvMenuTrackListContent > div').each(function(index){var attr=$(this).attr('afs');if(!(typeof attr!==typeof undefined&&attr!==false)){if($(this).is(":visible")){$(this).attr("afs","1");}
else{$(this).attr("afs","0");$(this).show();}}});$('#lblResultEmptySearchTrack').addClass('sDvSearchResult');$('#dvSearhResultText').show();$('#dvMenus .sDvMenuTrackListHeader').hide();$('#dvSearchTrack .sDvMenuTrackListHeader').show();$('#dvMenus .sDvMenuTrackListToBetBlank').hide();$('#dvMenus .sTlbTracksMenu a').hide();$('#dvMenuTT_Fav').hide();var foundValue=false;if(_searchTypeFilter===0){$(".sDvTracksColumnTrackName").each(function(i){if($(this).text().toLowerCase().indexOf(value.toLowerCase())>=0){$(this).parent().parent().parent().show();foundValue=true;}});}
else{if(_searchTypeFilter===1){$(".sDvTracksColumnTrackName").each(function(i){if($(this).parent().parent().attr('hasvideo')==='1'){$(this).parent().parent().parent().show();foundValue=true;}});}
if(_searchTypeFilter===2){$(".sDvTracksColumnTrackName").each(function(i){if($(this).parent().parent().attr('hasstats')==='1'){$(this).parent().parent().parent().show();foundValue=true;}});}
if(_searchTypeFilter===3){$(".sDvTracksColumnTrackName").each(function(i){if($(this).parent().parent().attr('hasvideo')==='1'&&$(this).parent().parent().attr('hasstats')==='1'){$(this).parent().parent().parent().show();foundValue=true;}});}}
if(foundValue){$('#lblResultEmptySearchTrack').hide();$('#dvMenuZone').removeClass('sDvSearchModeEmpty');}
else{$('#dvMenuZone').addClass('sDvSearchModeEmpty');$('#lblResultEmptySearchTrack').show();$('#lblResultEmptySearchTrack').find('div').html(messages.lblResultSearchEmpty);}
$('#dvMenus').addClass('sDvSearchMode');$('#dvSearchTrack').addClass('sDvSearchMode');}
else{$('#dvSearhResultText').hide();$('#lblResultEmptySearchTrack').removeClass('sDvSearchResult');$('#dvMenus .sDvMenuTrackListContent > div').each(function(index){if($(this).attr("afs")=="1"){$(this).removeAttr("afs");}
if($(this).attr("afs")=="0"){$(this).removeAttr("afs");$(this).hide();}});}}}
function BetSlipClickAction(){$('#dvTblBetSplipCart').removeClass('sTblBetSplipCartUnSelected ').addClass('sTblBetSplipCart');$('#dvTblBetSplipMyAccount').removeClass('sTblBetSplipMyAccount ').addClass('sTblBetSplipMyAccountUnSelected');$("#dvMyAccount").hide();$("#dvBetSlip").show();shoppingCart.ShowBetSlipInformation();if(typeof shoppingCartEdit!=="undefined"){shoppingCartEdit.HideBetSlipBetInformation();}
if($('#_modeBetting').val()=='0'){$("#dvAskLoginBetSlip").hide();$('#ucBetSlip_dvBetSlipImportantMessage').css('visibility','visible');$('#ucBetSlip_dvBetSlipImportantMessage').css('height','');$('#ucBetSlip_dvBetSlipMessageEmpty').css('visibility','visible');$('#ucBetSlip_dvBetSlipMessageEmpty').css('height','');$('.sDvBetSlipImportantMessage').show();if($(".spCountBets").text()!=0||shoppingCart.HaveTicketWithSomeError()){$('#ucBetSlip_trSendBet').show();}}
else{$("#dvAskLoginBetSlip").show();}
$('#dvTblBetSlipOpenBets').removeClass().addClass('sDvBetSlipOpenBets');if($(".spCountBets").text()!=0){$("#dvClearAllBet").removeClass('sHideElement');}
_enableHoverPopupMyAccount=true;}
function MyAccountClickAction(){$('#dvTblBetSplipCart').removeClass('sTblBetSplipCart').addClass('sTblBetSplipCartUnSelected');$('#dvTblBetSplipMyAccount').removeClass('sTblBetSplipMyAccountUnSelected').addClass('sTblBetSplipMyAccount');$('#dvTblBetSlipOpenBets').removeClass().addClass('sDvBetSlipOpenBets');$("#dvPopupMyAccount").hide();$("#dvBetSlip").hide();$("#dvAskLoginBetSlip").hide();$("#dvClearAllBet").addClass('sHideElement');if($('#_modeBetting').val()=='0'){$(".sDvMyAccountSettings").hide();}
$("#dvMyAccount").show();_enableHoverPopupMyAccount=false;}
function NavegateMobileVersion(hashTagId,acceptEmptyLikeHomePage){let valueCookie='';switch(hashTagId){case "TrackList":_sectionIsShowingModeMobile=0;setMobileMode();_trackSelected="";RefreshTrackListRace("","","","",false);break;case "RaceList":valueCookie=GetCookie("raceList");if(valueCookie!==''){valueCookie=valueCookie.replace("[RaceList]:","").split("//");ShowTrackInformationMobile(valueCookie[0],valueCookie[1],valueCookie[2],valueCookie[3],valueCookie[4]);}else{_sectionIsShowingModeMobileLast=_sectionIsShowingModeMobile;_sectionIsShowingModeMobile=1;setMobileMode();}
_sectionIsShowingModeMobile=1;SetValidateSession();break;case "RaceInfo":valueCookie=GetCookie("raceInfo");if(valueCookie!==''){valueCookie=valueCookie.replace("[RaceInfo]:","").split("//");ShowTrackInformation(valueCookie[0],valueCookie[1],valueCookie[2],valueCookie[3],valueCookie[4]);}
else{_sectionIsShowingModeMobileLast=_sectionIsShowingModeMobile;}
_sectionIsShowingModeMobile=2;SetValidateSession();break;case "BetCart":valueCookie=GetCookie("raceInfo");if(valueCookie!==''){valueCookie=valueCookie.replace("[RaceInfo]:","").split("//");ShowTrackInformation(valueCookie[0],valueCookie[1],valueCookie[2],valueCookie[3],valueCookie[4]);setTimeout(function(){$("#dvTblBetSplipCartMobile").click();},5);}else{_sectionIsShowingModeMobileLast=_sectionIsShowingModeMobile;}
_sectionIsShowingModeMobile=2;break;case "Top":switch(_sectionIsShowingModeMobileLast){case 0:NavegateMobileVersion("TrackList");break;case 1:NavegateMobileVersion("RaceList");break;case 2:NavegateMobileVersion("RaceInfo");break;}}}
function InitialBetSlip(){if(_readBackModeEnable){$('#dvTblBetSplipCart').click();}}
function renderUpcomingFeature(){if(_modePage===2){if(_sectionIsShowingModeMobile==0){return true;}
else{return false;}}
else{return true;}}
function setMobileMode(){if(_modePage===2){$('#tblRaceList').addClass('sHideElement');$("#lblTrack").addClass("sLblRootLink");if(_sectionIsShowingModeMobile==0){_isEnableRefresh=true;clearInformationRootMobileTrackName();clearInformationRootMobileMetting();clearInformationToRootMobileRace();$('#dvCentralZone').addClass('sHideElement');$('#dvMenuZone').removeClass('sHideElement');$('#dvResultZoneCurrent').addClass('sHideElement');$('#dvRaceListInformation').addClass('sHideElement');$('#dvRacePostTimeInformation').removeClass('sHideElement');$('#dvBannerMobileMenuRace').addClass('sHideElement');$('#dvRaceDetailInformation').addClass('sHideElement');if($('#_lsbsm').val()=='1'){$('#dvMobileStreaming').hide();}}
if(_sectionIsShowingModeMobile==1){_isEnableRefresh=false;$("#lblTrackNameRoot").removeClass("sLblRootLink");$("#lblMeetingRoot").removeClass("sLblRootLink");clearInformationToRootMobileRace();$('#dvCentralZone').removeClass('sHideElement');$('#dvMenuZone').addClass('sHideElement');$('#dvResultZoneCurrent').addClass('sHideElement');$('#dvTrackListToBet').addClass('sHideElement');$('#dvTrackListToBetZoneTop').addClass('sHideElement');$('.bettingMode').addClass('sHideElement');$('#dvRacePostTimeInformation').addClass('sHideElement');$('#dvRaceDetailInformation').addClass('sHideElement');$('#dvRaceListInformation').removeClass('sHideElement');$('#dvBannerMobileMenuRace').removeClass('sHideElement');if($('#_lsbsm').val()=='1'){$('#dvMobileStreaming').hide();}}
if(_sectionIsShowingModeMobile==2){_isEnableRefresh=true;$("#lblTrackNameRoot").addClass("sLblRootLink");$("#lblMeetingRoot").addClass("sLblRootLink");$('#dvCentralZone').removeClass('sHideElement');$('#dvMenuZone').addClass('sHideElement');$('#dvResultZoneCurrent').removeClass('sHideElement');$('#dvTrackListToBet').addClass('sHideElement');$('#dvTrackListToBetZoneTop').addClass('sHideElement');$('.bettingMode').removeClass('sHideElement');$('#dvRaceListInformation').addClass('sHideElement');$('#dvBannerMobileMenuRace').addClass('sHideElement');$('#dvRacePostTimeInformation').removeClass('sHideElement');$('#dvRaceDetailInformation').removeClass('sHideElement');if($('#_lsbsm').val()=='1'){if(_showExternalULRBetSlip){$('#dvMobileStreaming').show();}
else{$('#dvMobileStreaming').hide();}}}}
if(_modePage!=2){_isEnableRefresh=true;$('#dvSearchTrack').removeClass('sHideElement');$("#lblTrack").removeClass("sLblRootLink");$("#lblTrackNameRoot").removeClass("sLblRootLink");$("#lblMeetingRoot").removeClass("sLblRootLink");$("#lblRaceNumberRoot").removeClass("sLblRootLink");$('#dvCentralZone').removeClass('sHideElement');$('#dvResultZoneCurrent').removeClass('sHideElement');$('#dvMenuZone').removeClass('sHideElement');$('#dvTrackListToBet').removeClass('sHideElement');$('#tblRaceList').removeClass('sHideElement');$('.bettingMode').removeClass('sHideElement');$('#dvRaceListInformation').addClass('sHideElement');$('#dvBannerMobileMenuRace').addClass('sHideElement');$('#dvRacePostTimeInformation').removeClass('sHideElement');$('#dvRaceDetailInformation').removeClass('sHideElement');if(!_hasLoadExternalInformation){_hasLoadExternalInformation=true;LoadExternalInformation();LoadExternalInformationBetSlip();LoadExternalInformationUpcomingSports();LoadExternalInformationCasino();}
setInformationRootMobileTrackName($('#lblTrackName').text());if(ddTrackEventsLocalized!=undefined&&ddTrackEventsLocalized[this.indexMeeting]!=undefined){setInformationRootMobileMetting(ddTrackEventsLocalized[this.indexMeeting]);}
setInformationToRootMobile();}
setFocusRootMobile();}
function ChangeUpcomingFeaturedAccess(updateTrack){if(_controlWeight>=window.innerWidth){_controlWeight=window.innerWidth;if(window.innerWidth<=_maxWeightToFussionUpcomingFeatured){if(window.innerWidth<_maxWeightToFussionUpcomingFeaturedForMobile){if(!_maxWeightToFussionUpcomingChangedMobile){_maxWeightToFussionUpcomingChangedMobile=true;_maxWeightToFussionUpcomingChanged=false;_maxWeightToFussionUpcomingChangedFullSite=false;_modePage=2;setMobileMode();ShowBanner();if(updateTrack){RefreshTrackListRace("","","","",false);}}}
else{if(!_maxWeightToFussionUpcomingChanged){_maxWeightToFussionUpcomingChanged=true;_maxWeightToFussionUpcomingChangedMobile=false;_maxWeightToFussionUpcomingChangedFullSite=false;_modePage=1;setMobileMode();ShowBanner();if(updateTrack){RefreshTrackListRace("","","","",false);}}}}
else{if(!_maxWeightToFussionUpcomingChangedFullSite){_maxWeightToFussionUpcomingChangedFullSite=true;_maxWeightToFussionUpcomingChanged=false;_maxWeightToFussionUpcomingChangedMobile=false;_modePage=0;setMobileMode();ShowBanner();if(updateTrack){RefreshTrackListRace("","","","",false);}}}}
else{if(_controlWeight<window.innerWidth){_controlWeight=window.innerWidth;if(window.innerWidth>_maxWeightToFussionUpcomingFeatured){if(!_maxWeightToFussionUpcomingChangedFullSite){$.fancybox.close(false);_maxWeightToFussionUpcomingChangedFullSite=true;_maxWeightToFussionUpcomingChanged=false;_maxWeightToFussionUpcomingChangedMobile=false;_modePage=0;ShowBanner();setMobileMode();if(updateTrack){RefreshTrackListRace("","","","",false);}}}
else{if(window.innerWidth>=_maxWeightToFussionUpcomingFeaturedForMobile){if(!_maxWeightToFussionUpcomingChanged){_maxWeightToFussionUpcomingChanged=true;_maxWeightToFussionUpcomingChangedMobile=false;_maxWeightToFussionUpcomingChangedFullSite=false;_modePage=1;setMobileMode();ShowBanner();if(updateTrack){RefreshTrackListRace("","","","",false);}}}
else{if(!_maxWeightToFussionUpcomingChangedMobile){_maxWeightToFussionUpcomingChangedMobile=true;_maxWeightToFussionUpcomingChanged=false;_maxWeightToFussionUpcomingChangedFullSite=false;_modePage=2;setMobileMode();ShowBanner();if(updateTrack){RefreshTrackListRace("","","","",false);}}}}}}}
function SetBetSlipMenuMobile(){$('#dvBetSlipMobile').css('left',$('#dvCentralZone').outerWidth()+$('#dvMenuZone').outerWidth()-$('#dvBetSlipMobile').outerWidth()-6);}
function ShowBettingTools(divId){switch(divId){case 0:$('#dvBetZone').hide();$('#dvPassword').hide();$('#dvCustomizeBettingOptions').hide();$('#dvExternal').hide();$('#dvResultZone').hide();$('#dvBettingTools').show();$('#dvFavorite').show();break;case 1:$('#dvBetZone').hide();$('#dvFavorite').hide();$('#dvPassword').hide();$('#dvExternal').hide();$('#dvResultZone').hide();$('#dvBettingTools').show();$('#dvCustomizeBettingOptions').show();break;case 2:$('#dvBetZone').hide();$('#dvFavorite').hide();$('#dvCustomizeBettingOptions').hide();$('#dvExternal').hide();$('#dvResultZone').hide();$('#dvBettingTools').show();$('#dvPassword').show();break;}}
function ShowResulstByDate(){if(_modePage===2){_sectionIsShowingModeMobile=2;setMobileMode();}
if(_modePage!=0){$("#dvBetSlipClose").click();}
$('#dvBetZone').hide();$('#dvBettingTools').hide();$('#dvExternal').hide();$('#dvResultZoneCurrent').hide();$('#dvResultZone').show();$('#dvMainBetZone').show();ShowDatePickerResult();}
function ShowBetZone(){$('#dvBettingTools').hide();$('#dvExternal').hide();$('#dvResultZone').hide();$('#dvBetZone').show();$('#dvTrackListToBet').show();}
function ShowInitialDiv(){$('#dvBettingTools').hide();$('#dvResultZone').hide();$('#dvExternal').show();}
function ShowExternatURLBetSlip(){$('#dvExternalBetSlip').fadeIn();$('#dvExternalBetSlipUpcomingSport').fadeIn();}
function HideExternatURLBetSlip(){}
function SavePassword(){var button=document.getElementById(_btnSaveIdPassword);button.click();}
function ShowDatePickerResult(){var datePickerResult=$("#dvCalendarResults");ShowWaitDialog(true,$('.sDvResultReport').offset().top,$('.sDvResultReport').offset().left+($('.sDvResultReport').width()/2));datePickerResult.datepicker({onSelect:selectedResult,dateFormat:'yy/mm/dd',setDate:'+0d',minDate:'-1m',maxDate:'+0d'});datePickerResult.datepicker("setDate",new Date());let _resultDatePickerId=datePickerResult.datepicker('getDate');let dayMonth=datePickerResult.datepicker("option","monthNamesShort");var valueToShow=dayMonth[_resultDatePickerId.getMonth()]+' '+_resultDatePickerId.getDate();var value=_resultDatePickerId.getFullYear()+'/'+(_resultDatePickerId.getMonth()+1)+'/'+_resultDatePickerId.getDate();ShowResultTrackByEvent(value);datePickerResult.addClass('sHideElement');$('#dvDateResult').html('');createDynamicDropDown('sDvDropDownResultOption','resultOpion',new Array(),'',undefined,valueToShow,valueToShow,undefined,false,0,function(){var datePickerResult=$("#dvCalendarResults");datePickerResult.removeClass('sHideElement');if(isMobile.any()){if(_modePage===2){datePickerResult.css('left',$('#dvMainResultMettingCalendar').position().left+$('#dvMainResultMettingCalendar').width()-$('#dvCalendarResults').width());}
else{datePickerResult.css('left',$('#dvMainResultMettingCalendar').position().left+$('#dvMainResultMettingCalendar').width()-$('#dvCalendarResults').width());}}
else{datePickerResult.css('left',$('#dvMainResultMettingCalendar').position().left+$('#dvMainResultMettingCalendar').width()-$('#dvCalendarResults').width());}
setTimeout(function(){$(document).click(function(event){if(!$("#dvCalendarResults").hasClass('sHideElement')&&!($("#dvCalendarResults:hover").length>0)){$('#dvElementSelected_resultOpion').click();}});},250);},function(){var datePickerResult=$("#dvCalendarResults");datePickerResult.addClass('sHideElement');},document.getElementById('dvDateResult'));return false;}
function selectedResult(dateText,obj){let value=obj.selectedYear+'/'+(obj.selectedMonth+1)+'/'+obj.selectedDay;ShowResultTrackByEvent(value);let datePickerResult=$("#dvCalendarResults");let dayMonth=datePickerResult.datepicker("option","monthNamesShort");let _resultDatePickerId=datePickerResult.datepicker('getDate');let valueToShow=dayMonth[_resultDatePickerId.getMonth()]+' '+_resultDatePickerId.getDate();$('#lbDropDownElemenSelected_resultOpion').html(valueToShow);$('#dvElementSelected_resultOpion').click();}
function LoadExternalInformation(){setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.LoadExternalInformation("0",getPublicId(),"","",_sessionSSC,_token,addInformation,External_CallBack);},100);}
function LoadExternalInformationBetSlip(){if(_showExternalULRBetSlip){_externalInformationBetSlipNoLoaded=false;setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.LoadExternalInformation("1",getPublicId(),"","",_sessionSSC,_token,addInformation,ExternalBetSlip_CallBack);},100);}
else{_externalInformationBetSlipNoLoaded=true;}}
function LoadExternalInformationBetSlipVideo(url,forceLoad){$('#dvTrackWithVideo').hide();if(_showExternalULRBetSlip){if(_lastVideoURLLoaded!=url||forceLoad){_lastVideoURLLoaded=url;if(url!=''){$('#dvTrackWithVideo').show();setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.LoadExternalInformation("1",getPublicId(),"",url,_sessionSSC,_token,addInformation,ExternalBetSlip_CallBack);},100);}
else{$('#dvExternalBetSlip').html('');$('#dvExternalBetSlip').show();$('#dvMobileStreamingVideo').html('');$('#dvMobileStreaming').hide();}}}}
function LoadExternalInformationUpcomingSports(){setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.LoadExternalInformation("2",getPublicId(),"","",_sessionSSC,_token,addInformation,ExternalBetSlipSports_CallBack);},100);}
function LoadExternalInformationCasino(){setTimeout(function(){var addInformation=GetAddInformationBetSessionStorage();Racebook.LoadExternalInformation("3",getPublicId(),"","",_sessionSSC,_token,addInformation,ExternalBetSlipCasino_CallBack);},100);}
function External_CallBack(response){if(response.error===null){var obj=response.value.split(':::');if(obj[0]==='0'){let p=obj[1].indexOf("refresh");let h=obj[1].substring(0,p)+'lng='+$('#_lng').val()+'&'+obj[1].substring(p);$('#dvExternal').html(h);}
else{$('#dvExternal').hide();}}}
function ExternalBetSlip_CallBack(response){if(response.error===null){var obj=response.value.split(':::');if(obj[0]==='0'){if(_modePage===0){$('#dvExternalBetSlip').html(obj[1]);$('#dvExternalBetSlip').show();$('#dvMobileStreamingVideo').html('');$('#dvMobileStreaming').hide();}
else{if($('#_lsbsm').val()=='1'){if(_showExternalULRBetSlip){$('#dvMobileStreamingVideo').html(obj[1]);$('#dvMobileStreaming').show();}
else{$('#dvMobileStreamingVideo').html('');$('#dvMobileStreaming').hide();}}
else{$('#dvMobileStreamingVideo').html('');$('#dvMobileStreaming').hide();}}}
else{$('#dvExternalBetSlip *').html('');$('#dvExternalBetSlip').hide();}}}
function ExternalBetSlipSports_CallBack(response){if(response.error===null){var obj=response.value.split(':::');if(obj[0]==='0'){$('#dvExternalBetSlipUpcomingSport').html(obj[1]);$("#iframeUpcoming").iFrameResize({log:false,enablePublicMethods:false,checkOrigin:false,bodyMargin:0});}
else{$('#dvExternalBetSlipUpcomingSport').hide();}}}
function ExternalBetSlipCasino_CallBack(response){if(response.error===null){var obj=response.value.split(':::');if(obj[0]==='0'){if($('#dvExternalBetSlipCasino').html().trim()==''){try{if((obj[1].indexOf("WINTOPDOMMAIN-TO-REPLACE")>=0)){var domainAll=$(window.top.location).attr('host');obj[1]=obj[1].replace("WINTOPDOMMAIN-TO-REPLACE",domainAll);}
else if((obj[1].indexOf("DOMMAIN-TO-REPLACE")>=0)){var domainAll=$(location).attr('host');var domain=domainAll.replace(domainAll.split('.')[0],"").substr(1);obj[1]=obj[1].replace("DOMMAIN-TO-REPLACE",domain);}
else if((obj[1].indexOf("DOMMAINWITHSUB-TO-REPLACE")>=0)){var domainAll=$(location).attr('host');obj[1]=obj[1].replace("DOMMAINWITHSUB-TO-REPLACE",domainAll);}
if((obj[1].indexOf("PROTOCOL-TO-REPLACE")>=0)){var protocol=$(location).attr('protocol');obj[1]=obj[1].replace("PROTOCOL-TO-REPLACE",protocol);}
$('#dvExternalBetSlipCasino').html(obj[1]);}
catch(e){$('#dvExternalBetSlipCasino').hide();}}}
else{$('#dvExternalBetSlipCasino').hide();}}}
function ExternalBanner_CallBack(response){if(response.error===null){var obj=response.value.split(':::');if(obj[0]==='0'){let p=obj[1].indexOf("refresh");let h=obj[1].substring(0,p)+'lng='+$('#_lng').val()+'&'+obj[1].substring(p);$('#'+obj[2]).html(h);}
else{$('#'+obj[2]).hide();}}}
function showMyAccountMenu(isClick){if(isClick||$("#dvTblBetSplipMyAccount").hasClass("sTblBetSplipMyAccountUnSelected")){$("#dvLoginErrorMessage").hide();if($('#_anonimousLoginType').val()=="1"||$('#_anonimousLoginType').val()=="2"){showMyAccountOptionsPopup(isClick);$('.sDvFormMessage').addClass('sHideElement');$('.sDvFormLogin').removeClass('sHideElement');}
else{showMyAccountOptionsPopupMessage();$('.sDvFormLogin').addClass('sHideElement');$('.sDvFormMessage').removeClass('sHideElement');}
var top=$("#dvTblBetSplipMyAccount").offset().top;var left=$("#dvTblBetSplipMyAccount").offset().left;var leftMenu=parseInt($(".sDvCarBetMenuMyAccount").position().left+$("#dvTblBetSplipCart").width()+($(".sDvCarBetMenuMyAccount").width()),10)+5;if(_modePage===1||_modePage===2){leftMenu+=$('#dvBetSlipButtonCloseMobile').outerWidth()+$('#dvBetSlipButtonLineMobile').outerWidth();}
$('.sPositionArrowMyAccount').css('left',leftMenu+'px');$(".sInpLoginFormUsr").val('');$(".sInpPasswordFormUsr").val('');if(isClick||$('#dvTblBetSplipMyAccount:hover').length>0){if($('#_modeBetting').val()=='1'||($('#_modeBetting').val()=='0'&&$('#_isAnonimous').val()=='0')){$("#dvPopupMyAccount").show();resizeHeightFancyMyAccountPopup();}}}}
function resizeHeightFancyMyAccountPopup(){if(_modePage===1||_modePage===2){var menuBetSlipHeight=$('#tblBetSlip .sTdBetSlipTop').outerHeight();var loginHeight=$('#dvPopupMyAccount').outerHeight();var fancyHeight=$('.fancybox-inner').outerHeight();var dvBetSlipHeight=$('#dvBetSlip').outerHeight();if($('#dvPopupMyAccount').css('display')=='none'){loginHeight=0;}
if(fancyHeight<(loginHeight+menuBetSlipHeight)){$('.fancybox-inner').css('min-height',menuBetSlipHeight+loginHeight);}
else{if(loginHeight==0){$('.fancybox-inner').css('min-height',menuBetSlipHeight+dvBetSlipHeight);}}
resizeMainPage($('.fancybox-inner').outerHeight(),true);}}
function resizeMainPage(valueHeightToEvaluate,checkCurrenContent){var totalHeight=$('#dvRootMobile').outerHeight()+$('#dvContent').outerHeight();var heightToResize=0;if(valueHeightToEvaluate!=0){heightToResize+=valueHeightToEvaluate;}
if(heightToResize!=0){if(checkCurrenContent&&totalHeight<heightToResize){$('#dvContent').css('height',heightToResize+'px');}
if(!checkCurrenContent){$('#dvContent').css('height',heightToResize+'px');}}
else{$('#dvContent').css('height','');}}
function resizeHeightFancyDetailBet(){if(_modePage===1||_modePage===2){var menuBetSlipHeight=$('#tblBetSlip .sTdBetSlipTop').outerHeight();var dvAskLoginBetSlip=$('#dvAskLogin').outerHeight();var dvBetSlip=$('#dvBetSlip').height();var fancyHeight=$('.fancybox-inner').outerHeight();var detailBetHeight=8;if($('#dvAskLogin').css('display')=='none'){dvAskLoginBetSlip=0;}
if($('.sDvPopupBetDetail:visible').css('display')!=undefined&&$('.sDvPopupBetDetail:visible').css('display')!='none'){if(($('.sDvPopupBetDetail:visible').position().top+$('.sDvPopupBetDetail:visible').outerHeight())>fancyHeight){detailBetHeight+=($('.sDvPopupBetDetail:visible').position().top+$('.sDvPopupBetDetail:visible').outerHeight())-fancyHeight;}}
$('.fancybox-inner').css('height',dvAskLoginBetSlip+menuBetSlipHeight+dvBetSlip+detailBetHeight);resizeMainPage(dvAskLoginBetSlip+menuBetSlipHeight+dvBetSlip+detailBetHeight,false);}}
function restoreFancyMyAccountPopup(){if(_modePage===1||_modePage===2){$('.fancybox-inner').css('height','auto');}}
function showMyAccountOptionsPopup(isClick){if(_isAuthenticated){if($('#_modeBetting').val()=='1'){$("#optLogout").show();}
else{$("#optLogout").hide();}
$("#optLogin").hide();if(isClick){refreshMyAccountInformation(_isAuthenticated);$("#MainMenuMyAccount").show();SelMyAccount();}
else{$("#optAcctInfo").hide();$("#optCloseOpenSpot").show();$("#optFinalBets").show();$("#optActiveBets").show();$("#optResult").show();}}
else{$("#optLogin").show();$("#optLogout").hide();$("#optAcctInfo").hide();$("#optActiveBets").hide();$("#optFinalBets").hide();$("#optResult").hide();}}
function showMyAccountOptionsPopupMessage(){if(_isAuthenticated){if($('#_modeBetting').val()=='1'){$("#optLogout").show();}
else{$("#optLogout").hide();}
$("#optFinalBets").show();$("#optResult").show();$("#optLogin").hide();$("#optAcctInfo").hide();}
else{var messageBase=messages.lblMessageSignIn;var htmlMessage;if($('#_anonimousLoginType').val()=="0"){htmlMessage="<span>"+messageBase.replace('{0}',messages.lblSignIn)+"</span>";}
if($('#_anonimousLoginType').val()=="3"){var strURL=$("#loginURL").val();htmlMessage='<span onclick=\"GoURLLogin(\''+strURL+'\');\" class=\"sSpSignInUrl\">'+messageBase.replace('{0}',messages.lblSignIn)+'</span>';;}
$('#dvLoginMessageSignIn').html(htmlMessage);$("#optLogin").show();$("#optLogout").hide();$("#optAcctInfo").hide();$("#optActiveBets").hide();$("#optFinalBets").hide();$("#optResult").hide();}}
function GoURLLogin(url){window.top.location=url;}
function showMyAccountOptions(){if(_isAuthenticated){if($('#_modeBetting').val()=='0'){$("#dvMyAccountLogout").hide();$('#dvMyAccountTransactionHistory').hide();}
else{$("#dvMyAccountLogout").show();}
$("#dvMyAccounLogin").hide();$("#dvMyAccountInformation").show();$("#dvMyAccountActiveBet").show();$("#dvMyAccountFinalBet").show();$("#dvMyAccountRaceResult").show();$("#dvMyAccountConfiguration").show();$("#dvMyAccountPassword").show();$("#dvAccountInformation").show();}
else{$("#dvMyAccounLogin").show();$("#dvMyAccountLogout").hide();$("#dvMyAccountInformation").hide();$("#dvMyAccountActiveBet").hide();$("#dvMyAccountFinalBet").hide();$("#dvMyAccountRaceResult").hide();$("#dvMyAccountConfiguration").hide();$("#dvMyAccountPassword").hide();$("#dvAccountInformation").hide();}}
function focusClose(){$('.closejAlert').focus();}
function getPublicId(){if($('#_modeBetting').val()!='0'&&$('#_lsbs').val()=='1'){}
return publicId;}
function startLayoutAplication(){$('#dvShopCar').prepend($('#dvAccountInformationTemp').html());}