function TrackRaceListCollection(){var _count=0;this.Add=AddTrackInfo;this.AddFavorie=SetFavoriteRace;this.SortOrderNameAndMTP=SortOrderListNameAndMTP;this.SortOrderMTP=SortListOrderMTP;this.RemoveFavorie=RemoveFavoriteRace;this.SetStatsVideo=SetStatsVideoValue;this.Tracks=new Array();this.TotalCount=function(){return _count;};function AddInfo(collection,trackCode,name,race,mtp,isFeatured,trackEvent,raceId,trackType,isFavorite,featuredRaceName,haveFeaturedRaceName,internalSource,countryId,city,mtpSeconds,postTime,hv,hs){var toCloneRace=false;if(isFeatured=='1'){var foundFeaturedInList=false;for(var positionCollection=0;positionCollection<collection.length;positionCollection++){if(collection[positionCollection].TrackCode==trackCode){foundFeaturedInList=true;break;}}
if(!foundFeaturedInList){toCloneRace=true;}}
var index=collection.length;_count++;collection[index]=new Object;collection[index].TrackCode=trackCode;collection[index].Name=name;collection[index].Race=race;collection[index].MTP=mtp;collection[index].IsFeatured=isFeatured;collection[index].TrackEvent=trackEvent;collection[index].RaceId=raceId;collection[index].TrackType=trackType;collection[index].IsFavorite=isFavorite;collection[index].FeaturedRaceName=featuredRaceName;collection[index].HaveFeaturedRaceName=haveFeaturedRaceName;collection[index].InternalSource=internalSource;collection[index].CountryId=countryId;collection[index].City=city;collection[index].MTPSeconds=mtpSeconds;collection[index].PostTime=postTime;collection[index].HasVideo=hv===undefined?0:hv;collection[index].HasStats=hs===undefined?0:hs;if(typeof _trackEvent!=="undefined"){if(_trackEvent==trackEvent&&_trackCode==trackCode&&_raceId==raceId){if(_WagerInfo!=undefined&&mtpSeconds!=undefined&&postTime!=undefined){_WagerInfo.UpdateRaceMPT(raceId,mtpSeconds,postTime);}}}
if(toCloneRace){index=collection.length;collection[index]=new Object;collection[index].TrackCode=trackCode;collection[index].Name=name;collection[index].Race=race;collection[index].MTP=mtp;collection[index].IsFeatured="0";collection[index].TrackEvent=trackEvent;collection[index].RaceId=raceId;collection[index].TrackType=trackType;collection[index].IsFavorite=isFavorite;collection[index].FeaturedRaceName=featuredRaceName;collection[index].HaveFeaturedRaceName=haveFeaturedRaceName;collection[index].InternalSource=internalSource;collection[index].CountryId=countryId;collection[index].City=city;collection[index].MTPSeconds=mtpSeconds;collection[index].PostTime=postTime;collection[index].HasVideo=hv===undefined?0:hv;collection[index].HasStats=hs===undefined?0:hs;}}
function SortOrderListNameAndMTP(){this.Tracks.sort(function(a,b){if(a.Name!=b.Name){var nameA=replaceAll(a.Name,' ','');var nameB=replaceAll(b.Name,' ','');if(nameA.localeCompare(nameB)>0){return 1;}
if(nameA.localeCompare(nameB)<0){return-1;}}
else{if(typeof a.MTPSeconds!=="undefined"&&typeof b.MTPSeconds!=="undefined"){return a.MTPSeconds-b.MTPSeconds;}
else{return a.RaceId-b.RaceId;}}});}
function SetStatsVideoValue(hv,hs,ti,te){for(let i=0;i<this.Tracks.length;i++){if(this.Tracks[i].TrackCode==ti&&this.Tracks[i].TrackEvent==te){this.Tracks[i].HasVideo=hv?1:0;this.Tracks[i].HasStats=hs?1:0;$("#dvMenus").find('#'+this.Tracks[i].TrackCode).attr("hasvideo",this.Tracks[i].HasVideo);$("#dvMenus").find('#'+this.Tracks[i].TrackCode).attr("hasstats",this.Tracks[i].HasStats);}}}
function SortListOrderMTP(){this.Tracks.sort(function(a,b){if(typeof a.MTPSeconds!=="undefined"&&typeof b.MTPSeconds!=="undefined"){return a.MTPSeconds-b.MTPSeconds;}
else{return a.RaceId-b.RaceId;}});}
function AddTrackInfo(trackCode,name,race,mtp,isFeatured,trackEvent,raceId,trackType,isFavorite,featuredRaceName,haveFeaturedRaceName,internalSource,countryId,city,mtpSeconds,postTime){AddInfo(this.Tracks,trackCode,name,race,mtp,isFeatured,trackEvent,raceId,trackType,isFavorite,featuredRaceName,haveFeaturedRaceName,internalSource,countryId,city,mtpSeconds,postTime);}
function SetFavoriteRace(collection,trackCode){for(i=0;i<collection.length;i++){if(collection[i].TrackCode==trackCode){collection[i].IsFavorite="1";break;}}}
function RemoveFavoriteRace(collection,trackCode){for(i=0;i<collection.length;i++){if(collection[i].TrackCode==trackCode){collection[i].IsFavorite="0";break;}}}}
function TrackListCollection(){this.Add=AddTrackInfo;this.AddRace=AddRaceList;this.Tracks=new Array();function AddInfo(collection,trackEvent,trackCode,name,trackType,country,raceId){var index=collection.length;collection[index]=new Object;collection[index].TrackCode=trackCode;collection[index].Name=name;collection[index].TrackEvent=trackEvent;collection[index].TrackType=trackType;collection[index].Country=country;collection[index].RaceId=raceId;collection[index].RaceList=new Array();}
function AddRaceId(collection,trackEvent,trackCode,raceId){var index=-1;for(;index<collection.length;index++){if(index==-1){index=0;}
if(collection[index].TrackEvent==trackEvent&&collection[index].TrackCode==trackCode){break;}}
if(index!=-1){var indexRace=collection[index].RaceList.length;collection[index].RaceList[indexRace]=new Object;collection[index].RaceList[indexRace].RaceId=raceId;}}
function AddTrackInfo(trackEvent,trackCode,name,trackType,country,raceId){AddInfo(this.Tracks,trackEvent,trackCode,name,trackType,country,raceId);}
function AddRaceList(trackEvent,trackCode,raceId){AddRaceId(this.Tracks,trackEvent,trackCode,raceId);}}