var _trackSelected;var _searchSelected;var _hideThoroughbredSection=false;var _hideHarnessSection=false;var _hideGreyhoundSection=false;var _useTrackIdDeepLink=false;var _ifFromRemoveFavorite=false;var listObjectReadyAdd=new Array();function getPositionCountyOrder(contryToFind){var splitCountries=_menuTrackOrder.split(';');return splitCountries.indexOf(contryToFind);}
function SetImageFlagMenu(countryId,sufTrackType,sufCountry,isById,objectToSet,typeDefault){switch(countryId){case 'GB':case 'G1':if(isById){$('#dvMenuFlagImage'+sufTrackType+sufCountry).addClass('sTdMenuFlags sTdMenuFlagsGB');}else{$(objectToSet).addClass('sTdMenuFlags sTdMenuFlagsGB');}
break;default:if(isById){$('#dvMenuFlagImage'+sufTrackType+sufCountry).addClass('sTdMenuFlags sTdMenuFlagsUndefine sTdMenuFlags'+countryId);}else{$(objectToSet).addClass('sTdMenuFlags sTdMenuFlagsUndefine sTdMenuFlags'+countryId);}}}
function TrackMenuListRenderClass(){var activeRow=false;var _singleCss="sLinePrimary";var _alternatingCss="sLineSecondary";var _titleId="";var _headerId="";var _isAvailableTrack=true;var _trackTypeToLoad="";var _trackMsg="";var _favoriteMode=false;var _hideSection=false;var _setHeaderTitleId="";var _modeCountry=false;var _menuTrackOrder='US;CA;AU;GB;IE;HK;FR;ZA;AE;NZ;SA;JP;MX;KR;SE;SG;AR;CN;CL;VE;BR;UR;JM;PA;TR';var _sortOrderTable=new Array();this.Tracks=new Array();this.TrackMsg="";this.Show=ShowInfo;this.ShowSearch=ShowInfoSearch;this.ResetMenusAdded=resetMenusAdded;this.CleanMenusAdded=cleanMenusAdded;this.SetTrackMsg=setTrackMsg;this.GetTrackMsg=getTrackMsg;this.SetIsFavoriteMode=setIsFavoriteMode;this.GetIsFavoriteMode=getIsFavoriteMode;this.SetTitleId=setTitle;this.GetTitleId=getTitle;this.SetHeaderId=setHeader;this.GetHeaderId=getHeader;this.SetHeaderTitleId=setHeaderTitleId;this.SetTrackTypeToLoad=setTrackTypeToLoad;this.GetTrackTypeToLoad=getTrackTypeToLoad;this.SetIsAvailableTrack=setIsAvailableTrack;this.GetIsAvailableTrack=getIsAvailableTrack;this.SetModeByCountry=setModeByCountry;this.SetOrderCountries=setOrderCountries;this.SortOrderMenu=sortOrderSpecial;this.SetOrderMenuTrackList=setOrderMenuTrackList;this.GetMTPRace=getMTPRace;function setTrackMsg(value){_trackMsg=value;}
function getTrackMsg(){return _trackMsg;}
function setTitle(value){_titleId=value;}
function getTitle(){return _titleId;}
function setModeByCountry(value){_modeCountry=value;}
function setOrderCountries(value){_menuTrackOrder=value;_sortOrderTable=new Array();var listSortOrder=_menuTrackOrder.split(';');var positionSSOCountry=0;for(var positionSSO=0;positionSSO<listSortOrder.length;positionSSO++){var index;if(_modeByCountry){index=_sortOrderTable.length;_sortOrderTable[index]=new Object;_sortOrderTable[index].Country=listSortOrder[positionSSO];_sortOrderTable[index].Type='THB';_sortOrderTable[index].ValueSortOrder=positionSSOCountry;positionSSOCountry++;index=_sortOrderTable.length;_sortOrderTable[index]=new Object;_sortOrderTable[index].Country=listSortOrder[positionSSO];_sortOrderTable[index].Type='HRN';_sortOrderTable[index].ValueSortOrder=positionSSOCountry;positionSSOCountry++;index=_sortOrderTable.length;_sortOrderTable[index]=new Object;_sortOrderTable[index].Country=listSortOrder[positionSSO];_sortOrderTable[index].Type='GYN';_sortOrderTable[index].ValueSortOrder=positionSSOCountry;positionSSOCountry++;}
else{var listSortOrderCountry=listSortOrder[positionSSO].split('-')[0].split('/');for(positionSSOCountry=0;positionSSOCountry<listSortOrderCountry.length;positionSSOCountry++){index=_sortOrderTable.length;_sortOrderTable[index]=new Object;_sortOrderTable[index].Country=listSortOrderCountry[positionSSOCountry];_sortOrderTable[index].Type=listSortOrder[positionSSO].split('-')[1];_sortOrderTable[index].ValueSortOrder=100*positionSSO;}}}}
function setIsFavoriteMode(value){_favoriteMode=value;}
function getIsFavoriteMode(){return _favoriteMode;}
function setHeaderTitleId(value){_setHeaderTitleId=value;}
function setHeader(value){_headerId=value;}
function getHeader(){return _headerId;}
function setTrackTypeToLoad(value){_trackTypeToLoad=value;}
function getTrackTypeToLoad(){return _trackTypeToLoad;}
function setIsAvailableTrack(value){_isAvailableTrack=value;}
function getIsAvailableTrack(){return _isAvailableTrack;}
function sortOrderSpecial(){var contacts=$('#dvMenus'),cont=contacts.children('div');cont.detach().sort(function(a,b){var contentA=parseInt($(a).attr('sortOrder'));var contentB=parseInt($(b).attr('sortOrder'));return(contentA<contentB)?-1:(contentA>contentB)?1:0;});contacts.append(cont);}
function getPositioSorteOrder(countryId,type){var positionValue=-1;for(var positionSSO=0;positionSSO<_sortOrderTable.length;positionSSO++){if(_sortOrderTable[positionSSO].Country===countryId&&_sortOrderTable[positionSSO].Type===type){positionValue=_sortOrderTable[positionSSO].ValueSortOrder;return positionValue;}
if(_sortOrderTable[positionSSO].Country===countryId&&_sortOrderTable[positionSSO].Type==='*'){positionValue=_sortOrderTable[positionSSO].ValueSortOrder;return positionValue;}
if(_sortOrderTable[positionSSO].Country==='*'&&_sortOrderTable[positionSSO].Type===type){positionValue=_sortOrderTable[positionSSO].ValueSortOrder;return positionValue;}}
return positionValue;}
function ShowInfo(tableName,collectionName){ShowOnTableCountry(tableName,collectionName);return true;}
function setOrderMenuTrackList(){var newDiv;if(_modeCountry){var orderCountries=_menuTrackOrder.split(';');for(var positionCountCountry=0;positionCountCountry<orderCountries.length;positionCountCountry++){if(document.getElementById('dvMenuTT_THB'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvMenuTT_THB'+positionCountCountry;$(newDiv).attr('menuTrackType','THB');$(newDiv).attr('sortOrder',getPositioSorteOrder(orderCountries[positionCountCountry],'THB'));$('#dvMenus').append(newDiv);}
if(document.getElementById('dvMenuTT_HRN'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvMenuTT_HRN'+positionCountCountry;$(newDiv).attr('menuTrackType','HRN');$(newDiv).attr('sortOrder',getPositioSorteOrder(orderCountries[positionCountCountry],'HRN'));$('#dvMenus').append(newDiv);}
if(document.getElementById('dvMenuTT_GYN'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvMenuTT_GYN'+positionCountCountry;$(newDiv).attr('menuTrackType','GYN');$(newDiv).attr('sortOrder',getPositioSorteOrder(orderCountries[positionCountCountry],'GYN'));$('#dvMenus').append(newDiv);}}}
else{for(var positionSOS=0;positionSOS<_sortOrderTable.length;positionSOS++){var sortOrder=getPositioSorteOrder(_sortOrderTable[positionSOS].Country,_sortOrderTable[positionSOS].Type);if(sortOrder!==-1){if(document.getElementById('dvMenuTT_'+sortOrder)===null){newDiv=document.createElement('div');newDiv.id='dvMenuTT_'+sortOrder;$(newDiv).attr('menuTrackType',_sortOrderTable[positionSOS].Type);$(newDiv).attr('sortOrder',sortOrder);$('#dvMenus').append(newDiv);}}}}}
function AddMenusToList(value,mainContener){var existMenu=false;for(var positionList=0;positionList<listObjectReadyAdd.length;positionList++){if(listObjectReadyAdd[positionList].Value===value){listObjectReadyAdd[positionList].RowAdded=true;existMenu=true;break;}}
if(!existMenu){var index=listObjectReadyAdd.length;listObjectReadyAdd[index]=new Object;listObjectReadyAdd[index].Value=value;listObjectReadyAdd[index].RowAdded=true;listObjectReadyAdd[index].MainContener=mainContener;}}
function HasToClean(value){for(var positionList=0;positionList<listObjectReadyAdd.length;positionList++){if(listObjectReadyAdd[positionList].Value===value){return listObjectReadyAdd[positionList].RowAdded;}}
return false;}
function resetMenusAdded(){for(var positionList=0;positionList<listObjectReadyAdd.length;positionList++){listObjectReadyAdd[positionList].RowAdded=false;}}
function cleanMenusAdded(){var listObjectReadyAddTemp=listObjectReadyAdd;listObjectReadyAdd=new Array();for(var positionList=0;positionList<listObjectReadyAddTemp.length;positionList++){if(!listObjectReadyAddTemp[positionList].RowAdded){$('#'+listObjectReadyAddTemp[positionList].MainContener).remove();}
else{listObjectReadyAdd[listObjectReadyAdd.length]=listObjectReadyAddTemp[positionList];}}}
function ShowOnTableCountry(tableName,collection){var basicInformatioHTML=document.getElementById('dvMenuTrackType').outerHTML;var basicInformatioCountryHTML=document.getElementById('dvMenuInformationTrackTypeCountry').outerHTML;var sufTrackType='';var orderCountry=100;var orderCountryCountDefault=100;var addRow=false;for(i=0;i<collection.length;i++){var aDivRaceClick=document.createElement("a");var sufCountry='';var hasToSetHeader=false;aDivRaceClick.tabIndex="0";aDivRaceClick.onkeypress=function(e){if(event.which===13){$(this).find('div').first().click();}
event.preventDefault();event.stopPropagation();};aDivRaceClick.onfocus=function(){$(this).find('div').first().addClass('sDvHoverTrackMenu');};aDivRaceClick.onfocusout=function(){$(this).find('div').first().removeClass('sDvHoverTrackMenu');};if(_favoriteMode){sufTrackType='TT_Fav';sufCountry='C_Fav';}
else{if(_trackTypeToLoad==='FTR'){sufTrackType='TT_FTR';sufCountry='C_FTR';}
else if(_trackTypeToLoad==='UPC'){sufTrackType='TT_UPC';sufCountry='C_UPC';}
else{if(_modeCountry){orderCountry=getPositionCountyOrder(collection[i].CountryId);sufTrackType='TT_'+collection[i].TrackType+orderCountry;sufCountry='C_'+collection[i].CountryId;}
else{if(orderCountry===-1){orderCountry=orderCountryCountDefault;orderCountryCountDefault++;}
if(_trackTypeToLoad==='INT'){sufTrackType='TT_'+getPositioSorteOrder(collection[i].CountryId,_trackTypeToLoad);}else{sufTrackType='TT_'+getPositioSorteOrder(collection[i].CountryId,collection[i].TrackType);}
sufCountry='C_';}}}
if((_trackTypeToLoad===collection[i].TrackType||_favoriteMode||_trackTypeToLoad==='FTR'||_trackTypeToLoad==='UPC'||_trackTypeToLoad==='INT')&&sufTrackType.toString().indexOf("-1",0)===-1){var conteinerTrackTypeId=document.getElementById('dvMenu'+sufTrackType);var conteinerTrackTypeCountryId=document.getElementById('dvMenuInformation'+sufTrackType+sufCountry);var resultReplace;if(conteinerTrackTypeId===null){resultReplace=basicInformatioHTML.split('TrackType').join(sufTrackType);resultReplace=resultReplace.split('Country').join(sufCountry);if(_trackTypeToLoad==='UPC'||_trackTypeToLoad==='FTR'||_favoriteMode){$('#dvMenus').prepend(resultReplace);}
else{$('#dvMenus').append(resultReplace);}
hasToSetHeader=true;AddMenusToList('#dvMenuContentList'+sufTrackType+sufCountry,'dvMenuInformation'+sufTrackType+sufCountry);}
else{if(conteinerTrackTypeCountryId===null){resultReplace=basicInformatioCountryHTML.split('TrackType').join(sufTrackType);resultReplace=resultReplace.split('Country').join(sufCountry);$(conteinerTrackTypeId).append(resultReplace);hasToSetHeader=true;AddMenusToList('#dvMenuContentList'+sufTrackType+sufCountry,'dvMenuInformation'+sufTrackType+sufCountry);}
else{var hasToRemove=true;if(HasToClean('#dvMenuContentList'+sufTrackType+sufCountry)){hasToRemove=false;}
if(hasToRemove){$('#dvMenuContentList'+sufTrackType+sufCountry).html('');AddMenusToList('#dvMenuContentList'+sufTrackType+sufCountry,'dvMenuInformation'+sufTrackType+sufCountry);}}}
if(hasToSetHeader){$('#trMenuTitle'+sufTrackType+sufCountry).attr('onclick','MaximizeWindows(\'dvMenuContent'+sufTrackType+sufCountry+'\',\'bntMinimizeMaximize'+sufTrackType+sufCountry+'\')');if(_trackTypeToLoad==='THB'){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.MenuThoroughbredTracks);$('#tdMenuHorseImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='HRN'){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.MenuHarnessTracks);$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sTdMenuTrackListHeaderLeftHorseHarness');$('#tdMenuHorseImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='GYN'){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.MenuGreyhoundTracks);$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sTdMenuTrackListHeaderLeftGreyhound');$('#tdMenuHorseImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='INT'){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.MenuInternationalTracks);$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sTdMenuTrackListHeaderLeftInternational');$('#tdMenuHorseImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='FTR'){if($.trim(_labelTitleFeatured).length>0){$('#lnkRefreshTracks'+sufTrackType+sufCountry)[0].innerHTML=_labelTitleFeatured;}
else{$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.lblFeaturedRacesMessage);}
$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sTdMenuTrackListHeaderLeftFeatured');$('#tdMenuFlagImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='UPC'){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.lblUpcommingMessage);$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sMenuUpcomingRaceImage');$('#tdMenuFlagImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_trackTypeToLoad==='ALL'&&_favoriteMode){$('#lnkRefreshTracks'+sufTrackType+sufCountry).text(messages.MenuFavoriteTracks);$('#dvMenuHorseImage'+sufTrackType+sufCountry).attr('class','sTdMenuTrackListHeaderLeftHorseFavorite');$('#tdMenuFlagImage'+sufTrackType+sufCountry).attr('class','sHideElement');}
if(_modeCountry&&!_favoriteMode){SetImageFlagMenu(collection[i].CountryId,sufTrackType,sufCountry,true,'');}
else{$('#dvMenuFlagImage'+sufTrackType+sufCountry).addClass('sTdMenu'+_trackTypeToLoad);SetImageFlagMenu(collection[i].CountryId,sufTrackType,sufCountry,true,'');}}
var aRowDiv,aCellDiv,aCellDivFetured,aCellDivName,i,col;var isAlternating=false;var tlbTracks=returnObjById('dvMenuContentList'+sufTrackType+sufCountry);var tlbTracksHeader=returnObjById('dvMenuInformation'+sufTrackType+sufCountry);var tlbTracksLabel=returnObjById('spMenuContent'+sufTrackType+sufCountry);let tempDiv;let tempDiv2;if(tlbTracks===null){return false;}
if((_favoriteMode===false)||(_favoriteMode===true&&collection[i].IsFavorite==="1")){var hasToAddToCurrentMenu=false;if(((_isAvailableTrack||_isAvailableTrack==="True"||_trackTypeToLoad===collection[i].TrackType||_trackTypeToLoad==='ALL'||_trackTypeToLoad==='INT')&&collection[i].IsFeatured==="0")||(collection[i].IsFeatured==="1"&&_trackTypeToLoad==='FTR')){if(_modeCountry){hasToAddToCurrentMenu=true;}
else{if(_trackTypeToLoad==='INT'){if(getPositioSorteOrder(collection[i].CountryId,_trackTypeToLoad)!==-1&&getPositioSorteOrder(collection[i].CountryId,collection[i].TrackType)===-1){hasToAddToCurrentMenu=true;}}
else if(_trackTypeToLoad==='ALL'&&_favoriteMode===true){hasToAddToCurrentMenu=true;}
else if(getPositioSorteOrder(collection[i].CountryId,_trackTypeToLoad)!==-1&&getPositioSorteOrder(collection[i].CountryId,_trackTypeToLoad)===getPositioSorteOrder(collection[i].CountryId,collection[i].TrackType)){hasToAddToCurrentMenu=true;}
else{if(_trackTypeToLoad==='FTR'&&collection[i].IsFeatured==='1'){hasToAddToCurrentMenu=true;}}}}
if(hasToAddToCurrentMenu){let newTypeAttr=document.createAttribute("trackType");newTypeAttr.value=collection[i].TrackType;addRow=true;aRowDiv=document.createElement("div");aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasVideo");newTypeAttr.value=collection[i].HasVideo;aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasStats");newTypeAttr.value=collection[i].HasStats;aRowDiv.setAttributeNode(newTypeAttr);aRowDiv.id=_favoriteMode?'fv_'+collection[i].TrackCode:collection[i].TrackCode;aRowDiv.trackCode=collection[i].TrackCode;aRowDiv.raceId=collection[i].Race;aRowDiv.featuredRaceId=collection[i].RaceId;aRowDiv.trackEvent=collection[i].TrackEvent;aRowDiv.index=i;aRowDiv.nameTrack=collection[i].Name;aRowDiv.trackType=collection[i].TrackType;aRowDiv.trackTypeSource=_trackTypeToLoad;aRowDiv.onclick=clickOnTableRow;if(collection[i].IsFeatured==="1"){aRowDiv.isFeatured=true;aRowDiv.className="RaceFeatured";}
else{aRowDiv.isFeatured=false;}
if(!_favoriteMode){if(_useTrackIdDeepLink){$(aRowDiv).addClass("sIS_"+collection[i].TrackCode);}
else{$(aRowDiv).addClass("sIS_"+collection[i].InternalSource);}}
if(_trackSelected){if(_trackSelected.id===collection[i].TrackCode){if(_trackSelected.isFeatured){$(aRowDiv).addClass("RaceFeatured");}
else{$(aRowDiv).addClass("sTrackSelected");}}}
col=0;if(collection[i].HaveFeaturedRaceName==="1"){if(collection[i].IsFeatured==="1"){tempDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDivName=document.createElement("h1");aCellDiv=document.createElement("div");aCellDivFetured=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackName";aCellDivName.innerHTML=collection[i].FeaturedRaceName;aCellDivFetured.className="sDvTracksFeaturedIcon";aCellDiv.appendChild(aCellDivFetured);tempDiv.appendChild(aCellDivName);aCellDiv.appendChild(tempDiv);tempDiv2.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv2);}
else{tempDiv=document.createElement("div");tempDiv2=document.createElement("h1");aCellDiv=document.createElement("div");tempDiv2.innerHTML=collection[i].Name;aCellDiv.className="sDvTracksColumnTrackName";aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackRace";tempDiv2.innerHTML=collection[i].Race;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackMTP";tempDiv2.innerHTML=collection[i].MTP;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);aCellDiv=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackIconNext";aRowDiv.appendChild(aCellDiv);}
else{if(collection[i].IsFeatured==="1"){tempDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDivName=document.createElement("h1");aCellDiv=document.createElement("div");aCellDivFetured=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackName";aCellDivName.innerHTML=collection[i].Name;aCellDivFetured.className="sDvTracksFeaturedIcon";aCellDiv.appendChild(aCellDivFetured);tempDiv.appendChild(aCellDivName);aCellDiv.appendChild(tempDiv);tempDiv2.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv2);}
else{tempDiv=document.createElement("div");tempDiv2=document.createElement("h1");aCellDiv=document.createElement("div");tempDiv2.innerHTML=collection[i].Name;aCellDiv.className="sDvTracksColumnTrackName";aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackRace";tempDiv2.innerHTML=collection[i].Race;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");if(_favoriteMode){tempDiv2.innerHTML="<div class='sDvBtnBetZoneMenuFavoriteSelected' onclick=\"removeFavoriteFromMenu('"+collection[i].TrackCode+"','');return false\"><div></div></div>";aCellDiv.className="sDvTracksColumnFavorite";}
else{tempDiv2.innerHTML=collection[i].MTP;aCellDiv.className="sDvTracksColumnTrackMTP";}
aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);aCellDiv=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackIconNext";aRowDiv.appendChild(aCellDiv);}
aDivRaceClick.appendChild(aRowDiv);tlbTracks.appendChild(aDivRaceClick);}}}}
if(sufTrackType.indexOf(_trackTypeToLoad)!==-1||_favoriteMode){if(!addRow){$('#dvMenu'+sufTrackType).addClass('sHideElement');}else{$('#dvMenu'+sufTrackType).removeClass('sHideElement');}}
if(_trackTypeToLoad==='THB'&&_hideThoroughbredSection){$('#dvMenus div[menuTrackType="THB"]').addClass('sHideElement');}
if(_trackTypeToLoad==='HRN'&&_hideHarnessSection){$('#dvMenus div[menuTrackType="HRN"]').addClass('sHideElement');}
if(_trackTypeToLoad==='GYN'&&_hideGreyhoundSection){$('#dvMenus div[menuTrackType="GYN"]').addClass('sHideElement');}
$('#dvStartPosition').hide();return true;}
function ShowOnTable(tableName,collection){if(_setHeaderTitleId!==''){if($.trim(_labelTitleFeatured).length>0){$('#'+_setHeaderTitleId)[0].innerHTML=_labelTitleFeatured;}
else{$('#'+_setHeaderTitleId)[0].innerHTML=messages.lblFeaturedRacesMessage;}}
var tlbTracks=returnObjById(tableName);var tlbTracksHeader=returnObjById(_headerId);var tlbTracksLabel=returnObjById(_titleId);if(tlbTracks===null){return false;}
$(tlbTracks).html('');var aRowDiv,aCellDiv,aCellDivFetured,aCellDivName,i,col;var isAlternating=false;var addRow=false;let tempDiv;let tempDiv2;for(i=0;i<collection.length;i++){if(!_favoriteMode||(_favoriteMode&&collection[i].IsFavorite==="1")){if(((_isAvailableTrack||_isAvailableTrack==="True"||_trackTypeToLoad===collection[i].TrackType||_trackTypeToLoad==='ALL')&&collection[i].IsFeatured==="0")||(collection[i].IsFeatured==="1"&&_trackTypeToLoad==='FTR')){let newTypeAttr=document.createAttribute("trackType");newTypeAttr.value=collection[i].TrackType;addRow=true;aRowDiv=document.createElement("div");aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasVideo");newTypeAttr.value=collection[i].HasVideo;aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasStats");newTypeAttr.value=collection[i].HasStats;aRowDiv.setAttributeNode(newTypeAttr);aRowDiv.id=_favoriteMode?'fv_'+collection[i].TrackCode:collection[i].TrackCode;aRowDiv.trackCode=collection[i].TrackCode;aRowDiv.raceId=collection[i].Race;aRowDiv.featuredRaceId=collection[i].RaceId;aRowDiv.trackEvent=collection[i].TrackEvent;aRowDiv.index=i;aRowDiv.nameTrack=collection[i].Name;aRowDiv.trackType=collection[i].TrackType;aRowDiv.onclick=clickOnTableRow;if(collection[i].IsFeatured==="1"){aRowDiv.isFeatured=true;aRowDiv.className="RaceFeatured";}
else{aRowDiv.isFeatured=false;}
if(!_favoriteMode){if(_useTrackIdDeepLink){$(aRowDiv).addClass("sIS_"+collection[i].TrackCode);}
else{$(aRowDiv).addClass("sIS_"+collection[i].InternalSource);}}
col=0;if(collection[i].HaveFeaturedRaceName==="1"){if(collection[i].IsFeatured==="1"){tempDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDivName=document.createElement("h1");aCellDiv=document.createElement("div");aCellDivFetured=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackName";aCellDivName.innerHTML=collection[i].FeaturedRaceName;aCellDivFetured.className="sDvTracksFeaturedIcon";aCellDiv.appendChild(aCellDivFetured);tempDiv.appendChild(aCellDivName);aCellDiv.appendChild(tempDiv);tempDiv2.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv2);}
else{tempDiv=document.createElement("div");tempDiv2=document.createElement("h1");aCellDiv=document.createElement("div");tempDiv2.innerHTML=collection[i].FeaturedRaceName;aCellDiv.className="sDvTracksColumnTrackName";aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackRace";tempDiv2.innerHTML=collection[i].Race;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackMTP";tempDiv2.innerHTML=collection[i].MTP;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
else{if(collection[i].IsFeatured==="1"){tempDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDivName=document.createElement("h1");aCellDiv=document.createElement("div");aCellDivFetured=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackName";aCellDivName.innerHTML=collection[i].Name;aCellDivFetured.className="sDvTracksFeaturedIcon";aCellDiv.appendChild(aCellDivFetured);tempDiv.appendChild(aCellDivName);aCellDiv.appendChild(tempDiv);tempDiv2.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv2);}
else{tempDiv=document.createElement("div");tempDiv2=document.createElement("h1");aCellDiv=document.createElement("div");tempDiv2.innerHTML=collection[i].Name;aCellDiv.className="sDvTracksColumnTrackName";aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackRace";tempDiv2.innerHTML=collection[i].Race;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");if(_favoriteMode){tempDiv2.innerHTML="<div class='sDvBtnBetZoneMenuFavoriteSelected' onclick=\"removeFavoriteFromMenu('"+collection[i].TrackCode+"','');return false\"><div></div></div>";aCellDiv.className="sDvTracksColumnFavorite";}
else{tempDiv2.innerHTML=collection[i].MTP;aCellDiv.className="sDvTracksColumnTrackMTP";}
aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
if(!activeRow){if(!_trackSelected&&_trackSelected!==null){_trackSelected=aRowDiv;}
activeRow=true;}
tlbTracks.appendChild(aRowDiv);}}
if(_trackSelected){_trackSelected=returnObjById(_trackSelected.id);if(_trackSelected!==null&&_trackSelected){if(_trackSelected.isFeatured){_trackSelected.className="RaceFeatured";}
else{_trackSelected.className="sTrackSelected";}
$(_trackSelected).addClass('tblTrackRowSizeNormal');$(_trackSelected).find('.tblTracksColumnTrackRace').removeClass('tblTracksColumnTrackRace').addClass('tblTracksColumnTrackRaceAlternate');$(_trackSelected).find('.tblTracksColumnTrackMTP').removeClass('tblTracksColumnTrackMTP').addClass('tblTracksColumnTrackMTPAlternate');}}
if(_trackCodeOnSession){var rowTrack=returnObjById(_trackCodeOnSession);if(rowTrack){if(rowTrack.isFeatured){rowTrack.className="RaceFeatured";}
else{if(rowTrack){if(rowTrack.isFeatured){rowTrack.className="RaceFeatured";}
else{rowTrack.className='';}}
rowTrack.className='sTrackSelected';}
_trackSelected=rowTrack;}}}
if((!addRow)){if(_trackTypeToLoad==='THB'){_hideSection=_hideThoroughbredSection;}
if(_trackTypeToLoad==='HRN'){_hideSection=_hideHarnessSection;}
if(_trackTypeToLoad==='GYN'){_hideSection=_hideGreyhoundSection;}
if(_hideSection){if(tlbTracksHeader){tlbTracksHeader.style.display='none';}}
else{if(tlbTracksHeader){tlbTracksHeader.style.display='none';}
if(tlbTracksLabel){tlbTracksLabel.innerHTML=_trackMsg;}}}
else{if(tlbTracksHeader){tlbTracksHeader.style.display='';}
if(tlbTracksLabel){tlbTracksLabel.innerHTML='';}}
if((!addRow)&&_favoriteMode){if(tlbTracksLabel){tlbTracksLabel.innerHTML=_trackMsg;$(tlbTracks).parent().parent().parent().find('tr').click();$(tlbTracks).parent().hide();}}
$('#dvStartPosition').hide();return true;}
function ShowInfoSearch(tableName,collection){let tempDiv;let tempDiv2;let tempDiv3;var tlbTracks=returnObjById('dvMenuContentListSearch');var tlbTracksHeader=returnObjById('dvMenuInformationSearch');$(tlbTracks).html('');for(i=0;i<collection.length;i++){var aDivRaceClick=document.createElement("a");aDivRaceClick.tabIndex="0";var hasToSetHeader=false;if(tlbTracks===null){return false;}
var aRowDiv,aCellDiv,aCellDivTextSearch,aCellDivName;var i,col;var isAlternating=false;let newTypeAttr=document.createAttribute("trackType");newTypeAttr.value=collection[i].TrackType;addRow=true;aRowDiv=document.createElement("div");aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasVideo");newTypeAttr.value=collection[i].HasVideo;aRowDiv.setAttributeNode(newTypeAttr);newTypeAttr=document.createAttribute("hasStats");newTypeAttr.value=collection[i].HasStats;aRowDiv.setAttributeNode(newTypeAttr);aRowDiv.id=collection[i].TrackCode+'_'+replaceAll(collection[i].TrackEvent,'/','')+'_'+collection[i].RaceId+'_'+collection[i].RunnerPN;aRowDiv.trackCode=collection[i].TrackCode;aRowDiv.raceId=collection[i].Race;aRowDiv.featuredRaceId=collection[i].RaceId;aRowDiv.trackEvent=collection[i].TrackEvent;aRowDiv.runnerPN=collection[i].RunnerPN;aRowDiv.index=i;aRowDiv.nameTrack=collection[i].Name;aRowDiv.trackType=collection[i].TrackType;aRowDiv.trackTypeSource=_trackTypeToLoad;aRowDiv.onclick=function(){_searchSelected=this.trackCode+"_"+replaceAll(this.trackEvent,'/','')+"_"+this.featuredRaceId+"_"+this.runnerPN;ShowTrackInformation(this.trackCode,this.featuredRaceId,this.trackEvent,"",this.trackType);var foscuPN='tlbRunners1_ckb1__'+this.runnerPN;var foscuPNRow='tlbRunners1_tr_'+this.runnerPN;$("#dvCloseAdvancedSearch").click();setTimeout(function(){$('#'+foscuPN).focus();$('#'+foscuPNRow).addClass('sTrackSelectedSearch');},500);};aCellDiv=document.createElement("div");aCellDiv.className="sTdMenuFlagDimention";aCellDivName=document.createElement("div");aCellDivName.className="sTdMenuFlags";SetImageFlagMenu(collection[i].CountryId,'','',false,aCellDivName);aCellDiv.appendChild(aCellDivName);aRowDiv.appendChild(aCellDiv);aCellDiv=document.createElement("div");aCellDivTextSearch=document.createElement("div");aCellDivName=document.createElement("div");aCellDivName.innerHTML=collection[i].Name;aCellDivTextSearch.appendChild(aCellDivName);if(_searchType===0){aCellDivName=document.createElement("div");aCellDivName.innerHTML=collection[i].TrackEventText;aCellDivTextSearch.appendChild(aCellDivName);}
aCellDiv.appendChild(aCellDivTextSearch);aRowDiv.appendChild(aCellDiv);aCellDivTextSearch=document.createElement("div");aCellDivName=document.createElement("div");var aCellDivNameTemp=document.createElement("div");aCellDivNameTemp=document.createElement("div");aCellDivNameTemp.innerHTML=collection[i].RunnerPN+collection[i].RunnerLetter;aCellDivNameTemp.className="ProgramNumberT"+collection[i].RunnerPN;aCellDivName.appendChild(aCellDivNameTemp);aCellDivTextSearch.appendChild(aCellDivName);if(_searchType===0){var sCellNameSearch=document.createElement("div");aCellDivName=document.createElement("div");aCellDivName.innerHTML=collection[i].RunnerName;aCellDivName.className="sLabelRunner";sCellNameSearch.appendChild(aCellDivName);aCellDivName=document.createElement("div");aCellDivName.innerHTML=collection[i].RunnerDriver;sCellNameSearch.appendChild(aCellDivName);aCellDivTextSearch.className="sDvTracksColumnTrackName";aCellDivTextSearch.appendChild(sCellNameSearch);aCellDiv.appendChild(aCellDivTextSearch);tempDiv=document.createElement("div");tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);}
tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");aCellDiv.className="sDvTracksColumnTrackRace";tempDiv2.innerHTML=collection[i].RaceCode;aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);tempDiv=document.createElement("div");aCellDiv=document.createElement("div");tempDiv2=document.createElement("div");tempDiv2.innerHTML=collection[i].MTP;tempDiv3=document.createElement("div");tempDiv3.className="sDvTracksColumnTrackMTPIcon";if(parseInt(collection[i].MTPSeconds,10)<300){aCellDiv.className='sDvTracksColumnTrackMTP sDvTracksColumnTrackMTPNearPost';}
else{aCellDiv.className='sDvTracksColumnTrackMTP';}
aCellDiv.appendChild(tempDiv3);aCellDiv.appendChild(tempDiv2);tempDiv.appendChild(aCellDiv);aRowDiv.appendChild(tempDiv);aDivRaceClick=document.createElement("a");aDivRaceClick.appendChild(aRowDiv);tlbTracks.appendChild(aDivRaceClick);}
aCellDiv=document.createElement("div");if(collection.length>0){aCellDiv.innerHTML=(searchCollection.CurrentIndex+1)+' '+messages.Of+' '+searchCollection.TotalIndex;}
else{aCellDiv.innerHTML=messages.lblResultSearchEmpty;}
aCellDiv.className="sDvSearchState";tlbTracks.appendChild(aCellDiv);return true;}
function getMTPRace(trackEvent,trackId,raceId){for(i=0;i<this.Tracks.length;i++){if(this.Tracks[i].TrackEvent===trackEvent&&this.Tracks[i].TrackCode===trackId&&this.Tracks[i].RaceId===raceId){return collection[i].MTP;}}
return '';}
function highlightTableRow(){var tableObj=this.parentNode;if(tableObj.tagName!=='TABLE'){tableObj=tableObj.parentNode;}
if(this.isFeatured){$(this).addClass('RaceFeaturedOver');}
else{$(this).addClass('TrackRollOver');}
activeRow=this;}
function resetRowStyle(){var tableObj=this.parentNode;if(tableObj.tagName!=='TABLE'){tableObj=tableObj.parentNode;}
if(_trackSelected&&_trackSelected===this){if(this.isFeatured){this.className='RaceFeatured';}
else{this.className='sTrackSelected';}
$(this).find('.tblTracksColumnTrackRace').removeClass('tblTracksColumnTrackRace').addClass('tblTracksColumnTrackRaceAlternate');$(this).find('.tblTracksColumnTrackMTP').removeClass('tblTracksColumnTrackMTP').addClass('tblTracksColumnTrackMTPAlternate');return;}
if(this.isFeatured){this.className='RaceFeatured';}
else{this.className='tblTrackRowSizeNormal';}}
function clickOnTableRow(){_sectionIsShowingModeMobileLast=1;if(!_ifFromRemoveFavorite){if(_trackSelected){if(_trackSelected.isFeatured){_trackSelected.className='RaceFeatured';}
else{_trackSelected.className='tblTrackRowSizeNormal';}}
if(this.isFeatured){this.className='RaceFeatured';}
else{this.className='sTrackSelected';}
$(this).find('.tblTracksColumnTrackRace').removeClass('tblTracksColumnTrackRace').addClass('tblTracksColumnTrackRaceAlternate');$(this).find('.tblTracksColumnTrackMTP').removeClass('tblTracksColumnTrackMTP').addClass('tblTracksColumnTrackMTPAlternate');_trackSelected=this;ShowWaitDialog(true,$(this).offset().top,$(this).offset().left+($(this).width()/2));var loadRaceInformation=false;if(_modePage===0){loadRaceInformation=true;}
else{if(this.trackTypeSource==='UPC'||this.trackTypeSource==='FTR'){loadRaceInformation=true;}}
var valueSetCookie;if(loadRaceInformation){if(isMobile.any()){history.pushState("#RaceInfo",null,"#RaceInfo");if(_modeHashTagReloadMode){valueSetCookie="[RaceInfo]:"+this.trackCode+"//"+this.featuredRaceId+"//"+this.trackEvent+"//"+this.isFeatured+"//"+this.trackType;SetCookie("raceInfo",valueSetCookie,1);location.reload();return;}
else{ShowTrackInformation(this.trackCode,this.featuredRaceId,this.trackEvent,this.isFeatured,this.trackType);}}
else{ShowTrackInformation(this.trackCode,this.featuredRaceId,this.trackEvent,this.isFeatured,this.trackType);}}
else{history.pushState("#RaceList",null,"#RaceList");if(isMobile.any()){if(_modeHashTagReloadMode){valueSetCookie="[RaceList]:"+this.trackCode+"//"+this.featuredRaceId+"//"+this.trackEvent+"//"+this.isFeatured+"//"+this.trackType;SetCookie("raceList",valueSetCookie,1);location.reload();return;}
else{scrollToTop();ShowTrackInformationMobile(this.trackCode,this.featuredRaceId,this.trackEvent,this.isFeatured,this.trackType);}}
else{scrollToTop();ShowTrackInformationMobile(this.trackCode,this.featuredRaceId,this.trackEvent,this.isFeatured,this.trackType);}}}
_ifFromRemoveFavorite=false;}}
function TrackListResultRenderClass(){var activeRow=false;var _singleCss="sLinePrimary";var _alternatingCss="sLineSecondary";var _titleId="";var _headerId="";var _trackTypeToLoad="";var _trackMsg="";this.Tracks=new Array();this.TrackMsg="";this.Show=ShowInfo;this.SetTrackMsg=setTrackMsg;this.GetTrackMsg=getTrackMsg;this.SetTitleId=setTitle;this.GetTitleId=getTitle;this.SetHeaderId=setHeader;this.GetHeaderId=getHeader;function setTrackMsg(value){_trackMsg=value;}
function getTrackMsg(){return _trackMsg;}
function setTitle(value){_titleId=value;}
function getTitle(){return _titleId;}
function setHeader(value){_headerId=value;}
function getHeader(){return _headerId;}
function ShowInfo(tableName,collectionName){$('#dvResultTrackEvent').html('');var orderCountries=_menuTrackOrder.split(';');for(var positionCountCountry=0;positionCountCountry<orderCountries.length;positionCountCountry++){var newDiv;if(document.getElementById('dvResultTT_THB'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvResultTT_THB'+positionCountCountry;$(newDiv).attr('resultTrackType','THB');$('#dvResultTrackEvent').append(newDiv);}
if(document.getElementById('dvResultTT_HRN'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvResultTT_HRN'+positionCountCountry;$(newDiv).attr('resultTrackType','HRN');$('#dvResultTrackEvent').append(newDiv);}
if(document.getElementById('dvResultTT_GYN'+positionCountCountry)===null){newDiv=document.createElement('div');newDiv.id='dvResultTT_GYN'+positionCountCountry;$(newDiv).attr('resultTrackType','GYN');$('#dvResultTrackEvent').append(newDiv);}}
ShowOnTable(tableName,collectionName);return true;}
function ShowOnTable(tableName,collection){var basicInformatioHTML=document.getElementById('dvResultTrackType').outerHTML;var basicInformatioCountryHTML=document.getElementById('dvResultInformationTrackTypeCountry').outerHTML;var sufTrackType='';var sufCountry='';var tlbTracks=returnObjById(tableName);var tlbTracksHeader=returnObjById(_headerId);var tlbTracksLabel=returnObjById(_titleId);var orderCountryCountDefault=100;var aRow,aCell,divMain,divChild,divSubMain;var i,col;var isAlternating=false;var addRow=false;for(i=0;i<collection.length;i++){var hasToSetHeader=false;var orderCountry=getPositionCountyOrder(collection[i].Country);var mainId='dvResult'+sufTrackType+orderCountry;sufTrackType='TT_'+collection[i].TrackType+orderCountry;sufCountry='C_'+collection[i].Country;if(orderCountry===-1){orderCountry=orderCountryCountDefault;var newDiv=document.createElement('div');newDiv.id='dvResult'+sufTrackType+orderCountry;$(newDiv).attr('resultTrackType',collection[i].TrackType);$('#dvResultTrackEvent').append(newDiv);orderCountryCountDefault++;}
var conteinerTrackTypeId=document.getElementById('dvResult'+sufTrackType);var conteinerTrackTypeCountryId=document.getElementById('dvResultInformation'+sufTrackType+sufCountry);var resultReplace=basicInformatioCountryHTML.split('TrackType').join(sufTrackType);resultReplace=resultReplace.split('Country').join(sufCountry);if(conteinerTrackTypeId===null){resultReplace=basicInformatioHTML.split('TrackType').join(sufTrackType);resultReplace=resultReplace.split('Country').join(sufCountry);hasToSetHeader=true;$('#dvResultTrackEvent').append(resultReplace);}
else{if(conteinerTrackTypeCountryId===null){hasToSetHeader=true;resultReplace=basicInformatioCountryHTML.split('TrackType').join(sufTrackType);resultReplace=resultReplace.split('Country').join(sufCountry);$(conteinerTrackTypeId).append(resultReplace);}}
if(hasToSetHeader){if(collection[i].TrackType==='THB'){$('#spTracks'+sufTrackType+sufCountry).text(messages.MenuThoroughbredTracks);}
if(collection[i].TrackType==='HRN'){$('#spTracks'+sufTrackType+sufCountry).text(messages.MenuHarnessTracks);}
if(collection[i].TrackType==='GYN'){$('#spTracks'+sufTrackType+sufCountry).text(messages.MenuGreyhoundTracks);}
switch(collection[i].Country){case 'GB':case 'G1':$('#dvResultFlagImage'+sufTrackType+sufCountry).addClass('sTdResultFlagsGB');break;default:$('#dvResultFlagImage'+sufTrackType+sufCountry).addClass('sTdResultFlagsUndefine sTdResultFlags'+collection[i].Country);}}
tlbTracks=returnObjById('dvResultContentList'+sufTrackType+sufCountry);tlbTracksHeader=returnObjById('dvResultInformation'+sufTrackType+sufCountry);tlbTracksLabel=returnObjById('spResultContent'+sufTrackType+sufCountry);if(tlbTracks===null){return false;}
addRow=true;aRow=document.createElement('div');aCell=document.createElement('div');aCell.innerHTML=collection[i].Name;aRow.appendChild(aCell);aCell=document.createElement('div');for(r=0;r<collection[i].RaceList.length;r++){divChild=document.createElement('div');divChild.innerHTML=collection[i].RaceList[r].RaceId;divChild.trackCode=collection[i].TrackCode;divChild.trackEvent=collection[i].TrackEvent;divChild.raceId=collection[i].RaceList[r].RaceId;divChild.onclick=clickOnTableRow;aCell.appendChild(divChild);if(r+1!==collection[i].RaceList.length){divChild=document.createElement('div');divChild.innerHTML=' ';divChild.className='sDvSeparatorResult';aCell.appendChild(divChild);}}
aRow.appendChild(aCell);tlbTracks.appendChild(aRow);}
if((!addRow)){if(tlbTracksLabel){tlbTracksLabel.innerHTML=_trackMsg;}}
else{if(tlbTracksHeader){tlbTracksHeader.style.display='';}
if(tlbTracksLabel){tlbTracksLabel.innerHTML='';}}
if(!addRow){if(tlbTracksLabel){tlbTracksLabel.innerHTML=_trackMsg;}}
return true;}
function buttonHoverSort(objectId){$('#'+objectId).addClass('sTdBtnMaximizeResultHover');$('#'+objectId).removeClass('sTdBtnMaximizeResult');}
function buttonNormalSort(objectId){$('#'+objectId).addClass('sTdBtnMaximizeResult');$('#'+objectId).removeClass('sTdBtnMaximizeResultHover');}
function buttonHoverTrackName(objectId){$('#'+objectId).find('.sTdBtnMaximizeResult').addClass('sTdBtnMaximizeResultHover');$('#'+objectId).find('.sTdBtnMaximizeResult').removeClass('sTdBtnMaximizeResult');$('#'+objectId).addClass('TrackRollOverResult');}
function buttonNormalTrackName(objectId){$('#'+objectId).find('.sTdBtnMaximizeResultHover').addClass('sTdBtnMaximizeResult');$('#'+objectId).find('.sTdBtnMaximizeResultHover').removeClass('sTdBtnMaximizeResultHover');$('#'+objectId).removeClass('TrackRollOverResult');}
function highlightTableRow(){var tableObj=this.parentNode;if(tableObj.tagName!=='TABLE'){tableObj=tableObj.parentNode;}
$(this).addClass('TrackRollOver');activeRow=this;}
function resetRowStyle(){var tableObj=this.parentNode;if(tableObj.tagName!=='TABLE'){tableObj=tableObj.parentNode;}
this.className='tblTrackRowSizeNormal';}
function clickOnTableRow(){ShowTrackResultInformation(this.trackCode,this.trackEvent,this.raceId);}}
function orderResultByTrackType(){var sorting=[[0,0],[1,0]];$("#"+resultdMenuTrackListRace.TableName).trigger("sorton",[sorting]);}
function orderResultByName(){var sorting=[[1,0],[0,0]];$("#"+resultdMenuTrackListRace.TableName).trigger("sorton",[sorting]);}