function hideRunnersTables(){var tableName="tlbRunners",brName="br",raceName="race";var tlb,i=0,br,racelabel,k,stringHTML;k=_WagerInfo.PoolSelected().Size;for(i=1;i<=maxPickN;i++){tlb=returnObjById(tableName+i);br=returnObjById(brName+i);racelabel=returnObjById(raceName+i);if((tlb!==null)&&(br!==null)&&(racelabel!==null)){if((!isSafari)&&(!isChrome)){if(i>k){tlb.innerText='';}}
tlb.style.display='none';$(br).addClass('sHideElement');racelabel.style.display='none';}}}
function hideRunnersTablesSize(sizePoolType){var tableName="tlbRunners",brName="br",raceName="race";var tlb,i=0,br,racelabel,k,stringHTML;k=sizePoolType;for(i=1;i<=maxPickN;i++){tlb=returnObjById(tableName+i);br=returnObjById(brName+i);racelabel=returnObjById(raceName+i);if((tlb!==null)&&(br!==null)&&(racelabel!==null)){if((!isSafari)&&(!isChrome)){if(i>k){tlb.innerText='';}}
tlb.style.display='none';$(br).addClass('sHideElement');racelabel.style.display='none';}}}
function setBox(){var i=0;var j=0;var ctrlBox,ctrlBoxKey,ctrlckbAll;ctrlBox=document.getElementById("ckbBox");ctrlBoxKey=document.getElementById("ckbBoxKey");if((ctrlBoxKey!=null)&&(ctrlBox!=null)){if(ctrlBox.checked){unCheckCheckbox(document.getElementById('dvCkbBox'));$('.sSpNormalSelection').removeClass('sHideElement');}
else{checkCheckbox(document.getElementById('dvCkbBox'));unCheckCheckbox(document.getElementById('dvCkbBoxKey'));$('.sSpNormalSelection').addClass('sHideElement');}
for(i=1;i<4;i++){ctrlckbAll=returnObjById("ckbBox_"+i);if(ctrlckbAll){ctrlckbAll.disabled=ctrlBox.checked;ctrlckbAll.checked=false;disableControl("ckbBox_"+i,ctrlBox.checked);}}
for(i=0;i<ArrayBoxOptions.length;i++){for(j=1;j<ArrayBoxOptions[i].length;j++){if(ctrlBoxKey.checked){disableControl(ArrayBoxOptions[i][j],false);}
else{disableControl(ArrayBoxOptions[i][j],ctrlBox.checked);}}}
for(let i=0;i<ArrayBoxInvalidOptions.length;i++){if(ArrayBoxInvalidOptions[i]!==undefined){for(let j=1;j<ArrayBoxInvalidOptions[i].length;j++){if(ctrlBoxKey.checked){disableControl(ArrayBoxInvalidOptions[i][j],false);}
else{disableControl(ArrayBoxInvalidOptions[i][j],ctrlBox.checked);}}}}}
GenerateTotalCombination();}
function SetBoxAllLine(dvCtrlBox,lineNumber){var i=0;var ctrlBox=$(dvCtrlBox).find('input');if(ctrlBox!=null){for(let i=0;i<ArrayBoxOptions.length;i++){if($(ctrlBox).prop('checked')){checkCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement);}
else{unCheckCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement);}}}}
function SetBoxAllLineReverse(control){if(control.id.indexOf('dvtlbRunners')>=0){let tableId=parseInt(control.id.split('_')[0].replace('dvtlbRunners',''),10);let lineNumber=parseInt(control.id.split('_')[1].replace('ckb',''),10);let lineNumberBox=lineNumber-1;let totalChecked=0;let total=0;let baseId='tlbRunners'+tableId+'_ckb'+lineNumber;let boxAllId='';$("#tlbRunners"+tableId+" tbody input").each(function(index){if($(this).attr('id').indexOf(baseId)>=0){total=total+1;if($(this).prop('checked')){totalChecked=totalChecked+1;}}});if(_poolCodeSelected<8){boxAllId='dvCkbBox_'+lineNumberBox;}
else{if(_poolCodeSelected<1000){boxAllId='dvCkbBox_tlbRunners'+tableId;}}
if($('#'+boxAllId+' input').prop('checked')&&totalChecked!==total){checkOrUnCheckCheckbox(document.getElementById(boxAllId));}
if(!$('#'+boxAllId+' input').prop('checked')&&totalChecked===total){checkOrUnCheckCheckbox(document.getElementById(boxAllId));}}}
function CheckOnlyOneInAllLine(dvCtrlBox,lineNumber){if(typeof shoppingCartEdit!=="undefined"&&shoppingCartEdit.IsEditMode()){for(let i=0;i<ArrayBoxOptions.length;i++){if(dvCtrlBox!=document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement){unCheckCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement);}}
checkOrUnCheckCheckbox(dvCtrlBox);}
else{let isValidToCheck=false;if(_parlayType===ParlayType.MultiTrackCombined){if($('#'+dvCtrlBox.id).hasClass('checkBoxChecked')){isValidToCheck=true;}
else{let rPn=dvCtrlBox.id.toString().split('__')[1];isValidToCheck=!controlTicket.GetTicketInformation().GetBetInformation().ExistBetDetail(_trackEvent,_trackCode,_raceId,rPn);}}
else{isValidToCheck=true;}
if(isValidToCheck){for(let i=0;i<ArrayBoxOptions.length;i++){if(dvCtrlBox!==document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement){unCheckCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement,true);}}
checkOrUnCheckCheckbox(dvCtrlBox,true);if($('#'+dvCtrlBox.id).hasClass('checkBoxChecked')){AddParlayEntrie(dvCtrlBox);}
else{if(!$('#'+dvCtrlBox.id).hasClass('checkBoxChecked')){let rP=1;if(dvCtrlBox.id.toString().indexOf('_ckb2')>0){rP=2;}
if(dvCtrlBox.id.toString().indexOf('_ckb3')>0){rP=3;}
RemoveParlayEntrie(rP);ShowBetParlay();}}}
else{alert(messages.lblErrorAddBetParlayMoreThanTwoEntries);}}}
function SetCheckedControls(controlCollection,lineNumber,state){var i=0;for(i=0;i<controlCollection.length;i++){var control=document.getElementById(ArrayBoxOptions[i][lineNumber]);if(control!=null){if(state){checkCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement);}
else{unCheckCheckbox(document.getElementById(ArrayBoxOptions[i][lineNumber]).parentElement);}}}}
function SetBoxAllLinePick(dvCtrlBox,tableIdToCheck){var ctrlBox=$(dvCtrlBox).find('input');if(ctrlBox!=null){$("#"+tableIdToCheck+" input").each(function(index){if(ctrlBox.attr('id')!=$(this).attr('id')){if($(ctrlBox).prop('checked')){checkCheckbox(document.getElementById($(this).attr('id')).parentElement);}
else{unCheckCheckbox(document.getElementById($(this).attr('id')).parentElement);}}});}}
function factorial(n){let total=1;for(i=1;i<=n;i++){total=total*i;}
return total;}
function GenerateTotalCombination(){let combinationsTotal=0;let combinationGenerate=new Array();let totalPosition1=0;let totalPosition2=0;let totalPosition3=0;let totalPosition4=0;let totalPosition5=0;let totalPosition6=0;switch(_WagerInfo.PoolType()){case PoolType.Quinella:case PoolType.Exacta:if($('#ckbBox').prop('checked')){for(var position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){totalPosition1++;}}
if(totalPosition1>1){combinationsTotal=factorial(totalPosition1)/factorial(totalPosition1-2);if(_WagerInfo.PoolType()===PoolType.Quinella){combinationsTotal/=2;}}}
else{if($('#ckbBoxKey').prop('checked')){for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){var index=0;if(ExistCombinationEx(combinationGenerate,position,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;}
if(_WagerInfo.PoolType()===PoolType.Exacta){if(ExistCombinationEx(combinationGenerate,position2,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position;}}}}}}}
else{for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){var foundValue=false;if(_WagerInfo.PoolType()==PoolType.Quinella){for(var position3=0;combinationGenerate.length>position3&&!foundValue;position3++){if(combinationGenerate[position3][0]==position2&&combinationGenerate[position3][1]==position){foundValue=true;}}}
if(!foundValue){let index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;}}}}}}
for(let position3=0;combinationGenerate.length>position3;position3++){if(combinationGenerate[position3][0]!=combinationGenerate[position3][1]){totalPosition1++;}}
if(totalPosition1!==0){combinationsTotal=totalPosition1;}}
break;case PoolType.Trifecta:if($('#ckbBox').prop('checked')){for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){totalPosition1++;}}
if(totalPosition1>2){combinationsTotal=factorial(totalPosition1)/factorial(totalPosition1-3);}}
else{if($('#ckbBoxKey').prop('checked')){for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){for(let position3=0;ArrayBoxOptions.length>position3;position3++){if($('#'+ArrayBoxOptions[position3][2]).prop('checked')){let index=0;if(ExistCombinationTri(combinationGenerate,position,position2,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position3;}
if(ExistCombinationTri(combinationGenerate,position,position3,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position2;}
if(ExistCombinationTri(combinationGenerate,position2,position,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position3;}
if(ExistCombinationTri(combinationGenerate,position2,position3,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position;}
if(ExistCombinationTri(combinationGenerate,position3,position,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position2;}
if(ExistCombinationTri(combinationGenerate,position3,position2,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position;}}}}}}}}
else{for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){for(let position3=0;ArrayBoxOptions.length>position3;position3++){if($('#'+ArrayBoxOptions[position3][2]).prop('checked')){let index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position3;}}}}}}}
for(let position3=0;combinationGenerate.length>position3;position3++){if(combinationGenerate[position3][0]!=combinationGenerate[position3][1]&&combinationGenerate[position3][0]!=combinationGenerate[position3][2]&&combinationGenerate[position3][1]!=combinationGenerate[position3][2]){totalPosition1++;}}
if(totalPosition1!=0){combinationsTotal=totalPosition1;}}
break;case PoolType.Superfecta:if($('#ckbBox').prop('checked')){for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){totalPosition1++;}}
if(totalPosition1>3){combinationsTotal=factorial(totalPosition1)/factorial(totalPosition1-4);}}
else{if($('#ckbBoxKey').prop('checked')){for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){for(let position3=0;ArrayBoxOptions.length>position3;position3++){if($('#'+ArrayBoxOptions[position3][2]).prop('checked')){for(let position4=0;ArrayBoxOptions.length>position4;position4++){if($('#'+ArrayBoxOptions[position4][3]).prop('checked')){let index=0;if(ExistCombinationSuper(combinationGenerate,position,position2,position3,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position,position2,position4,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position,position3,position2,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position,position3,position4,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position,position4,position2,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position,position4,position3,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position2,position,position3,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position2,position,position4,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position2,position3,position,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position2,position3,position4,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position;}
if(ExistCombinationSuper(combinationGenerate,position2,position4,position,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position2,position4,position3,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position2;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position;}
if(ExistCombinationSuper(combinationGenerate,position3,position,position2,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position3,position,position4,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position3,position2,position,position4)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position4;}
if(ExistCombinationSuper(combinationGenerate,position3,position2,position4,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position4;combinationGenerate[index][3]=position;}
if(ExistCombinationSuper(combinationGenerate,position3,position4,position,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position3,position4,position2,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position3;combinationGenerate[index][1]=position4;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position;}
if(ExistCombinationSuper(combinationGenerate,position4,position,position2,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position4,position,position2,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position4,position,position3,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position4,position2,position,position3)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position3;}
if(ExistCombinationSuper(combinationGenerate,position4,position2,position3,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position;}
if(ExistCombinationSuper(combinationGenerate,position4,position3,position,position2)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position;combinationGenerate[index][3]=position2;}
if(ExistCombinationSuper(combinationGenerate,position4,position3,position2,position)){index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position4;combinationGenerate[index][1]=position3;combinationGenerate[index][2]=position2;combinationGenerate[index][3]=position;}}}}}}}}}}
else{for(let position=0;ArrayBoxOptions.length>position;position++){if($('#'+ArrayBoxOptions[position][0]).prop('checked')){for(let position2=0;ArrayBoxOptions.length>position2;position2++){if($('#'+ArrayBoxOptions[position2][1]).prop('checked')){for(let position3=0;ArrayBoxOptions.length>position3;position3++){if($('#'+ArrayBoxOptions[position3][2]).prop('checked')){for(let position4=0;ArrayBoxOptions.length>position4;position4++){if($('#'+ArrayBoxOptions[position4][3]).prop('checked')){let index=combinationGenerate.length;combinationGenerate[index]=new Array();combinationGenerate[index][0]=position;combinationGenerate[index][1]=position2;combinationGenerate[index][2]=position3;combinationGenerate[index][3]=position4;}}}}}}}}}
for(let position3=0;combinationGenerate.length>position3;position3++){if(combinationGenerate[position3][0]!=combinationGenerate[position3][1]&&combinationGenerate[position3][0]!=combinationGenerate[position3][2]&&combinationGenerate[position3][0]!=combinationGenerate[position3][3]&&combinationGenerate[position3][1]!=combinationGenerate[position3][2]&&combinationGenerate[position3][1]!=combinationGenerate[position3][3]&&combinationGenerate[position3][2]!=combinationGenerate[position3][3]){totalPosition1++;}}
if(totalPosition1!=0){combinationsTotal=totalPosition1;}}
break;case PoolType.DailyDouble:case PoolType.PickN:var positionPick=1;for(let position=0;ArrayBoxOptions.length>position;position++){if(ArrayBoxOptions[position]==="---------------"){positionPick++;}
else{if($('#'+ArrayBoxOptions[position]).prop('checked')){switch(positionPick){case 1:totalPosition1++;break;case 2:totalPosition2++;break;case 3:totalPosition3++;break;case 4:totalPosition4++;break;case 5:totalPosition5++;break;case 6:totalPosition6++;break;}}}}
switch(positionPick){case 2:if(totalPosition1>0&&totalPosition2>0){combinationsTotal=totalPosition1*totalPosition2;}
break;case 3:if(totalPosition1>0&&totalPosition2>0&&totalPosition3>0){combinationsTotal=totalPosition1*totalPosition2*totalPosition3;}
break;case 4:if(totalPosition1>0&&totalPosition2>0&&totalPosition3>0&&totalPosition4>0){combinationsTotal=totalPosition1*totalPosition2*totalPosition3*totalPosition4;}
break;case 5:if(totalPosition1>0&&totalPosition2>0&&totalPosition3>0&&totalPosition4>0&&totalPosition5>0){combinationsTotal=totalPosition1*totalPosition2*totalPosition3*totalPosition4*totalPosition5;}
break;case 6:if(totalPosition1>0&&totalPosition2>0&&totalPosition3>0&&totalPosition4>0&&totalPosition5>0&&totalPosition6>0){combinationsTotal=totalPosition1*totalPosition2*totalPosition3*totalPosition4*totalPosition5*totalPosition6;}
break;}
break;case PoolType.Parlay:case PoolType.WinParlay:case PoolType.PlaceParlay:case PoolType.ShowParlay:case PoolType.WinPlaceParlay:case PoolType.WinShowParlay:case PoolType.PlaceShowParlay:case PoolType.WinPlaceShowParlay:if(controlTicket!==undefined){for(let ict=0;ict<controlTicket.TicketList.length;ict++){let ct=controlTicket.TicketList[ict];if(ct!==undefined){for(let ib=0;ib<ct.BetList.length;ib++){let b=ct.BetList[ib];if(b!==undefined){if(b.PoolTypeId>=1000){let totalDetails=0;for(let ibd=0;ibd<b.BetDetailList.length;ibd++){let bd=b.BetDetailList[ibd];if(bd!==undefined){totalDetails++;}}
switch(b.PoolTypeId){case 1000:case 1001:case 1002:case 1003:if(totalDetails>1){combinationsTotal++;}
break;case 1004:case 1005:case 1006:if(totalDetails>1){combinationsTotal++;combinationsTotal++;}
break;case 1007:if(totalDetails>1){combinationsTotal++;combinationsTotal++;combinationsTotal++;}
break;}}}}}}
break;}}
if(parseInt(combinationsTotal,10)>0){$('.aSendBet').addClass('aSendBetEnable');}
else{$('.aSendBet').removeClass('aSendBetEnable');}
var textToSet=messages.lblTotalBetInformation.toString().replace('{0}',combinationsTotal);textToSet=textToSet.replace('{1}',shoppingCart.CurrencyISO+' '+FormatCurrency(combinationsTotal*parseFloat($('#betAmount').val()),true));$('#lblTotalBetInformation').text(textToSet);}
function ExistCombinationEx(arrayOriginal,value1,value2){let existCombination=true;for(let position4=0;arrayOriginal.length>position4;position4++){if(arrayOriginal[position4][0]==value1&&arrayOriginal[position4][1]==value2){existCombination=false;break;}}
return existCombination;}
function ExistCombinationTri(arrayOriginal,value1,value2,value3){let existCombination=true;for(let position4=0;arrayOriginal.length>position4;position4++){if(arrayOriginal[position4][0]==value1&&arrayOriginal[position4][1]==value2&&arrayOriginal[position4][2]==value3){existCombination=false;break;}}
return existCombination;}
function ExistCombinationSuper(arrayOriginal,value1,value2,value3,value4){let existCombination=true;for(let position4=0;arrayOriginal.length>position4;position4++){if(arrayOriginal[position4][0]==value1&&arrayOriginal[position4][1]==value2&&arrayOriginal[position4][2]==value3&&arrayOriginal[position4][3]==value4){existCombination=false;break;}}
return existCombination;}
function FormatCurrency(num,isSpecial){num=num.toString().replace(/\$|\,/g,'');if(isNaN(num)){num="0";}
var sign=(num==(num=Math.abs(num)));num=Math.floor(num*100+0.50000000001);var cents=num%100;num=Math.floor(num/100).toString();if(cents<10){cents="0"+cents;}
for(var i=0;i<Math.floor((num.length-(1+i))/3);i++){num=num.substring(0,num.length-(4*i+3))+','+num.substring(num.length-(4*i+3));}
if(!isSpecial||(isSpecial&&parseFloat(cents)>0)){return(((sign)?'':'-')+num+'.'+cents);}
else{return(((sign)?'':'-')+num+'');}}