$(document).ready(function(){$("#promo-more-details").on("click",function(){$("#promo-more-details").hide();$("#promo-less-details").show();});$("#promo-less-details").on("click",function(){$("#promo-more-details").show();$("#promo-less-details").hide();});});function copyPromo(elem){var copyText=$(elem).find(".promo-name").text();navigator.clipboard.writeText(copyText);$(elem).addClass("active");setTimeout(function(){$(elem).removeClass("active");},3000);}
function promoMainFilterClick(event){$('.betus-promo-filter ul li').removeClass('active');$(event).addClass('active');$('.available-promo-container').css('display','block');$('.available-promo-item-container .promo-list').css('display','block');if($(event).attr('data-mainFilter')==="available"){$('.available-promo-filter ul li').removeClass('active');$('.available-promo-filter ul li[data-filter="all"]').addClass('active');$('.available-promo-item-container .promo-list').each(function(){if($(this).data('claimed')==="True"){$(this).css('display','none');}});}
if($(event).attr('data-mainFilter')==="claimed"){var count=0;$('.available-promo-container').css('display','none');$('.available-promo-item-container .promo-list').css('display','none');$('.available-promo-item-container .promo-list').each(function(){if($(this).data('claimed')==="True"){$(this).css('display','block');count++;}});$('.claimed-count').text(count);}}
function promoFilterClick(event){const selectedTab=$(event).text();$('.available-promo-filter ul li').removeClass('active');$(event).addClass('active');$('.filter-text').text($(event).attr('data-filter'));$('.available-promo-container').css('display','block');$('.available-promo-item-container .promo-list').css('display','block');if($(event).attr('data-filter')==="all"){$('.available-promo-item-container .promo-list').each(function(){if($(this).data('claimed')==="True"){$(this).css('display','none');}});}
if($(event).attr('data-filter')!=="all"){promoTabClick($(event).text());}
setNoPromos(selectedTab);}
function setNoPromos(selectedTab){selectedTab=selectedTab?.toLowerCase();const promoList=(selectedTab.toLowerCase()!=='all')?$(`div.promo-list[data-${selectedTab}="${selectedTab.toUpperCase()}"][data-claimed="False"]`):$('.available-promo-item-container .promo-list[data-claimed="False"]');if(promoList.length){$('#noPromoMsg').addClass('d-none');}else{$('#noPromoMsg').removeClass('d-none');}}
function promoDropdown(event){if(!$(event).hasClass('active')){$(event).addClass('active');$('.promo-filter-dropdown').css('display','block');}else{$(event).removeClass('active');$('.promo-filter-dropdown').css('display','none');}}
function promoTabClick(selectTab){$('.available-promo-item-container .promo-list').css('display','none');$('.available-promo-item-container .promo-list').each(function(){if($(this).data(selectTab.toLowerCase())===selectTab.toUpperCase()&&$(this).data('claimed')==="False"){$(this).css('display','block');}});if(selectTab=='casino'){sortPromo(selectTab);}}
function sortPromo(selectTab){const promoDivs=document.querySelectorAll('div[data-index-'+selectTab+']');const promoDivArray=Array.from(promoDivs);promoDivArray.sort((a,b)=>{const dataIndexA=parseInt(a.getAttribute('data-index-'+selectTab));const dataIndexB=parseInt(b.getAttribute('data-index-'+selectTab));return dataIndexA-dataIndexB;});const parentElement=promoDivArray[0].parentNode;Array.from(parentElement.children).forEach(child=>{if(!promoDivArray.includes(child)){child.style.display='none';}});promoDivArray.forEach(div=>{parentElement.appendChild(div);});}